//! Install and uninstall poly's git-hook shims.
//!
//! Ported (and retargeted to `poly`) from `polyhooks/src/cli/install.rs`. Each
//! installed `.git/hooks/<hook-type>` script is a tiny POSIX-shell shim that
//! resolves `poly` from `PATH` and execs it as:
//!
//! ```sh
//! exec poly hooks hook-impl --hook-type=<hook-type> -- "$@"
//! ```
//!
//! No absolute path is baked into the shim: it always runs whatever `poly` is
//! current on the user's PATH, and fails loudly with an explanatory message when
//! `poly` is not found rather than letting the git operation silently succeed.
//! That message distinguishes a genuinely missing install from an install that is
//! in flight or unreachable from this hook's `PATH` — see [`HOOK_TMPL`].
//!
//! The store/workspace/provisioning machinery, the `core.hooksPath` refusal
//! logic, legacy-hook *execution* chaining (migration mode), and
//! `init_template_dir` are intentionally **not** ported — they are out of scope
//! for the crate-side shims (and `polyhooks` is removed in B4). The caller
//! (`poly-cli`) resolves the hooks directory via [`crate::git::get_git_hooks_dir`]
//! and passes it in.

use std::io::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::ValueEnum as _;

use crate::stage::HookType;

/// Marker embedded in every poly-generated shim so install/uninstall can tell a
/// poly shim apart from a user's own hook. Bump the suffix if the template
/// changes in a way that requires re-installation.
const HOOK_MARKER: &str = "poly-hook-shim:v1";

/// Shell template for an installed git-hook shim.
///
/// `[HOOK_TYPE]` is replaced with the kebab-case hook name. The shim resolves
/// `poly` from `PATH` at hook time — no absolute path is baked in, so it always
/// runs whatever `poly` is current on the user's PATH. When `poly` is not found
/// it fails loudly with an explanatory message instead of letting the git
/// operation proceed as though the hook had passed. `exec` replaces the shell
/// process, so the hook's stdin (used by `pre-push`) and arguments are forwarded
/// transparently.
///
/// Because the shims are installed per repository but `poly` is resolved
/// globally, a missing `poly` blocks *every* commit on the machine — so the
/// failure path is worth diagnosing precisely. Before printing "not installed"
/// the shim looks for evidence of the two states that are not a missing install:
/// a staged, not-yet-renamed copy (an install in flight) and a `poly` that is
/// installed somewhere this hook's `PATH` cannot see. Each branch names the file
/// it found, so a stale leftover is self-evident rather than a silent
/// misdiagnosis; with no evidence at all the original message stands, with the
/// possibility of an in-flight install merely mentioned. Every branch still
/// exits non-zero: the hook fails closed.
///
/// The `poly-hook-shim:v1` marker is deliberately *not* bumped when this text
/// changes — [`is_our_shim`] recognises shims by that exact marker, so bumping it
/// would orphan shims written by an older poly. `poly hooks install` rewrites a
/// recognised shim unconditionally, which is how this text reaches existing
/// installs.
static HOOK_TMPL: &str = r#"#!/bin/sh
# File generated by poly. Do not edit.
# poly-hook-shim:v1

# Report why `poly` could not be resolved, as "<kind> <path>":
#   staged <path>      a not-yet-renamed copy is present -> an install is in flight
#   partial <path>     a `poly` file exists but is not executable -> half-written install
#   unreachable <path> poly is installed, but its directory is not on this hook's PATH
# Prints nothing when there is no evidence. Runs inside a command substitution,
# so its IFS / positional-parameter changes stay contained.
poly_missing_evidence() {
    IFS=:
    set -f
    # shellcheck disable=SC2086 # deliberate word split of PATH on ':'
    set -- $PATH "${CARGO_HOME:-${HOME}/.cargo}/bin" "${HOME}/.local/bin"
    set +f
    unset IFS

    staged='' partial='' unreachable=''
    for dir in "$@"; do
        [ -n "$dir" ] && [ -d "$dir" ] || continue
        for candidate in "$dir"/poly.tmp* "$dir"/poly.new* "$dir"/poly.partial \
            "$dir"/poly-*.tmp "$dir"/.poly.tmp* "$dir"/.poly-* "$dir"/cargo-install*/poly \
            "$dir"/poly.exe.tmp* "$dir"/poly.exe.new*; do
            if [ -f "$candidate" ] && [ -z "$staged" ]; then
                staged=$candidate
            fi
        done
        for name in poly poly.exe; do
            if [ -f "$dir/$name" ] && [ ! -x "$dir/$name" ] && [ -z "$partial" ]; then
                partial="$dir/$name"
            fi
            if [ -x "$dir/$name" ] && [ -z "$unreachable" ]; then
                unreachable="$dir/$name"
            fi
        done
    done

    if [ -n "$staged" ]; then
        printf 'staged %s\n' "$staged"
    elif [ -n "$partial" ]; then
        printf 'partial %s\n' "$partial"
    elif [ -n "$unreachable" ]; then
        printf 'unreachable %s\n' "$unreachable"
    fi
}

if ! command -v poly >/dev/null 2>&1; then
    evidence=$(poly_missing_evidence)
    kind=${evidence%% *}
    found=${evidence#* }
    echo 'poly: cannot run the [HOOK_TYPE] git hook: the `poly` binary is not on your PATH.' >&2
    case "$kind" in
        staged | partial)
            echo '  A partially-installed poly is present:' >&2
            echo "    ${found}" >&2
            echo '  so poly looks like it is being installed or upgraded right now. Wait for that' >&2
            echo '  to finish, then re-run your git command. If that path is a stale leftover from' >&2
            echo '  a failed install, delete it and re-install poly.' >&2
            ;;
        unreachable)
            echo '  poly is installed here:' >&2
            echo "    ${found}" >&2
            echo '  but that directory is not on the PATH this hook sees. Add it to your PATH (or' >&2
            echo '  to the environment your git client runs with) and re-run your git command.' >&2
            ;;
        *)
            echo '  These hooks were installed by `poly hooks install`. Install poly and make sure' >&2
            echo '  it is on your PATH, or run `poly hooks uninstall` to remove them. If poly is' >&2
            echo '  being re-installed right now, wait for that to finish and retry - this hook' >&2
            echo '  fails closed rather than skipping your checks.' >&2
            ;;
    esac
    exit 1
fi

exec poly hooks hook-impl --hook-type=[HOOK_TYPE] -- "$@"
"#;

/// Default file mode for an installed shim (owner rwx, group/other rx).
#[cfg(unix)]
const HOOK_MODE: u32 = 0o755;

/// Resolve the set of hook types to act on: an explicit list, or all ten
/// git-triggered hook types when `requested` is empty.
fn resolve_types(requested: &[HookType]) -> Vec<HookType> {
    if requested.is_empty() {
        HookType::value_variants().to_vec()
    } else {
        requested.to_vec()
    }
}

/// Path of the `.legacy` sibling for a given hook name.
fn legacy_path(hooks_dir: &Path, hook_type: HookType) -> PathBuf {
    hooks_dir.join(format!("{}.legacy", hook_type.as_ref()))
}

/// Render the shim script for `hook_type`.
///
/// The shim carries no absolute path — it resolves `poly` from `PATH` at hook
/// time — so nothing needs shell-quoting into the script.
fn render_shim(hook_type: HookType) -> String {
    HOOK_TMPL.replace("[HOOK_TYPE]", hook_type.as_ref())
}

/// Whether `path` is a shim that poly generated (by marker content).
///
/// A missing file is treated as "not ours" rather than an error.
fn is_our_shim(path: &Path) -> Result<bool> {
    match std::fs::read_to_string(path) {
        Ok(content) => Ok(content.contains(HOOK_MARKER)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(err) => Err(err.into()),
    }
}

/// Write `script` to `path` atomically (write a sibling tmp file, set the exec
/// bit on it, then rename into place), so an interrupted install never leaves a
/// half-written, unmanaged hook behind.
fn write_shim(path: &Path, script: &str) -> Result<()> {
    let tmp = path.with_extension("poly-tmp");
    {
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open(&tmp)
            .with_context(|| format!("failed to open hook shim tmp `{}`", tmp.display()))?;
        file.write_all(script.as_bytes())
            .with_context(|| format!("failed to write hook shim tmp `{}`", tmp.display()))?;
    }

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let mut perms = tmp
            .metadata()
            .with_context(|| format!("failed to read permissions for `{}`", tmp.display()))?
            .permissions();
        perms.set_mode(HOOK_MODE);
        std::fs::set_permissions(&tmp, perms)
            .with_context(|| format!("failed to set exec bit on `{}`", tmp.display()))?;
    }

    std::fs::rename(&tmp, path).with_context(|| format!("failed to install hook shim `{}`", path.display()))?;
    Ok(())
}

/// Install a single hook shim, preserving any pre-existing foreign hook.
fn install_one(hooks_dir: &Path, hook_type: HookType, overwrite: bool) -> Result<PathBuf> {
    let hook_path = hooks_dir.join(hook_type.as_ref());
    let legacy = legacy_path(hooks_dir, hook_type);

    if hook_path.try_exists()? {
        if overwrite {
            if legacy.try_exists()? {
                std::fs::remove_file(&legacy).with_context(|| format!("failed to remove `{}`", legacy.display()))?;
            }
        } else if !is_our_shim(&hook_path)? {
            if legacy.try_exists()? {
                anyhow::bail!(
                    "cannot preserve existing hook `{}`: `{}` already exists; \
                     remove or rename it, or re-run with overwrite",
                    hook_path.display(),
                    legacy.display()
                );
            }
            std::fs::rename(&hook_path, &legacy).with_context(|| {
                format!(
                    "failed to preserve existing hook `{}` as `{}`",
                    hook_path.display(),
                    legacy.display()
                )
            })?;
        }
    }

    write_shim(&hook_path, &render_shim(hook_type))?;
    Ok(hook_path)
}

/// Install poly git-hook shims into `hooks_dir`.
///
/// When `hook_types` is empty, all ten git-triggered hook types are installed.
/// Each shim resolves `poly` from `PATH` at hook time (no absolute path is
/// recorded). A pre-existing non-poly hook is preserved as `<name>.legacy`
/// (unless `overwrite` is set, which discards it). Returns the paths of the
/// shims that were written.
pub fn install(hooks_dir: &Path, hook_types: &[HookType], overwrite: bool) -> Result<Vec<PathBuf>> {
    std::fs::create_dir_all(hooks_dir)
        .with_context(|| format!("failed to create hooks dir `{}`", hooks_dir.display()))?;

    let types = resolve_types(hook_types);
    let mut installed = Vec::with_capacity(types.len());
    for hook_type in types {
        installed.push(install_one(hooks_dir, hook_type, overwrite)?);
    }
    Ok(installed)
}

/// Uninstall poly git-hook shims from `hooks_dir`, restoring any preserved
/// `<name>.legacy` hook.
///
/// When `hook_types` is empty, all ten git-triggered hook types are considered.
/// Hooks not managed by poly are left untouched. Returns the paths of the shims
/// that were removed.
pub fn uninstall(hooks_dir: &Path, hook_types: &[HookType]) -> Result<Vec<PathBuf>> {
    let types = resolve_types(hook_types);
    let mut removed = Vec::new();

    for hook_type in types {
        let hook_path = hooks_dir.join(hook_type.as_ref());
        let legacy = legacy_path(hooks_dir, hook_type);

        if is_our_shim(&legacy)? {
            std::fs::remove_file(&legacy).with_context(|| format!("failed to remove `{}`", legacy.display()))?;
        }

        if !is_our_shim(&hook_path)? {
            continue;
        }

        std::fs::remove_file(&hook_path).with_context(|| format!("failed to remove `{}`", hook_path.display()))?;
        removed.push(hook_path.clone());

        if legacy.try_exists()? {
            std::fs::rename(&legacy, &hook_path).with_context(|| {
                format!(
                    "failed to restore legacy hook `{}` to `{}`",
                    legacy.display(),
                    hook_path.display()
                )
            })?;
        }
    }

    Ok(removed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn install_writes_shim_with_exec_line() {
        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");

        let written = install(&hooks, &[HookType::PreCommit], false).expect("install");

        let shim = hooks.join("pre-commit");
        assert_eq!(written, vec![shim.clone()]);

        let content = std::fs::read_to_string(&shim).expect("read shim");
        assert!(
            content.contains("exec poly hooks hook-impl --hook-type=pre-commit -- \"$@\""),
            "shim missing exec line:\n{content}"
        );
        assert!(content.contains(HOOK_MARKER));
        assert!(
            content.contains("command -v poly"),
            "shim missing PATH guard:\n{content}"
        );
        assert!(
            !content.contains("/usr/bin/poly"),
            "shim should not bake an absolute path:\n{content}"
        );
    }

    #[cfg(unix)]
    #[test]
    fn install_sets_executable_bit() {
        use std::os::unix::fs::PermissionsExt as _;

        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");
        install(&hooks, &[HookType::PreCommit], false).expect("install");

        let mode = std::fs::metadata(hooks.join("pre-commit"))
            .expect("metadata")
            .permissions()
            .mode();
        assert_eq!(mode & 0o111, 0o111, "shim is not executable: {mode:o}");
    }

    #[test]
    fn install_with_empty_list_writes_all_ten_shims() {
        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");
        let written = install(&hooks, &[], false).expect("install");
        assert_eq!(written.len(), 10);
    }

    #[test]
    fn install_preserves_foreign_hook_and_uninstall_restores_it() {
        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");
        std::fs::create_dir_all(&hooks).expect("mkdir");

        let pre_commit = hooks.join("pre-commit");
        let original = "#!/bin/sh\necho legacy hook\n";
        std::fs::write(&pre_commit, original).expect("write foreign hook");

        install(&hooks, &[HookType::PreCommit], false).expect("install");

        let legacy = hooks.join("pre-commit.legacy");
        assert!(legacy.exists(), "foreign hook was not preserved");
        assert!(
            std::fs::read_to_string(&pre_commit)
                .expect("read shim")
                .contains(HOOK_MARKER),
            "shim was not installed over the foreign hook"
        );

        let removed = uninstall(&hooks, &[HookType::PreCommit]).expect("uninstall");
        assert_eq!(removed, vec![pre_commit.clone()]);
        assert!(!legacy.exists(), "legacy hook was not restored");
        assert_eq!(std::fs::read_to_string(&pre_commit).expect("read restored"), original);
    }

    /// Install the `pre-commit` shim into `hooks` and run it with a synthetic
    /// `PATH`/`HOME`, so the diagnostic branches can be exercised for real.
    #[cfg(unix)]
    fn run_pre_commit_shim(hooks: &Path, fake_bin: &Path, fake_home: &Path) -> std::process::Output {
        install(hooks, &[HookType::PreCommit], false).expect("install");
        std::process::Command::new("/bin/sh")
            .arg(hooks.join("pre-commit"))
            .env_clear()
            .env("PATH", fake_bin)
            .env("HOME", fake_home)
            .output()
            .expect("run shim")
    }

    #[cfg(unix)]
    #[test]
    fn shim_reports_a_missing_install_when_there_is_no_evidence_of_one() {
        let dir = TempDir::new().expect("tempdir");
        let bin = dir.path().join("bin");
        let home = dir.path().join("home");
        std::fs::create_dir_all(&bin).expect("mkdir");
        std::fs::create_dir_all(&home).expect("mkdir");

        let output = run_pre_commit_shim(&dir.path().join("hooks"), &bin, &home);
        let stderr = String::from_utf8_lossy(&output.stderr);

        assert_eq!(output.status.code(), Some(1), "hook must fail closed:\n{stderr}");
        assert!(
            stderr.contains("Install poly and make sure"),
            "expected the not-installed message:\n{stderr}"
        );
        assert!(
            !stderr.contains("being installed or upgraded right now"),
            "must not claim a mid-upgrade without evidence:\n{stderr}"
        );
    }

    #[cfg(unix)]
    #[test]
    fn shim_reports_a_mid_upgrade_when_a_staged_copy_is_present() {
        let dir = TempDir::new().expect("tempdir");
        let bin = dir.path().join("bin");
        let home = dir.path().join("home");
        std::fs::create_dir_all(&bin).expect("mkdir");
        std::fs::create_dir_all(&home).expect("mkdir");
        let staged = bin.join("poly.tmp.4242");
        std::fs::write(&staged, "half a binary").expect("write staged copy");

        let output = run_pre_commit_shim(&dir.path().join("hooks"), &bin, &home);
        let stderr = String::from_utf8_lossy(&output.stderr);

        assert_eq!(output.status.code(), Some(1), "hook must fail closed:\n{stderr}");
        assert!(
            stderr.contains("being installed or upgraded right now"),
            "expected the mid-upgrade message:\n{stderr}"
        );
        assert!(
            stderr.contains(staged.to_str().expect("utf-8 path")),
            "expected the staged path as evidence:\n{stderr}"
        );
    }

    #[cfg(unix)]
    #[test]
    fn shim_reports_an_off_path_install_when_poly_lives_outside_path() {
        let dir = TempDir::new().expect("tempdir");
        let bin = dir.path().join("bin");
        let home = dir.path().join("home");
        let cargo_bin = home.join(".cargo/bin");
        std::fs::create_dir_all(&bin).expect("mkdir");
        std::fs::create_dir_all(&cargo_bin).expect("mkdir");

        let installed = cargo_bin.join("poly");
        std::fs::write(&installed, "#!/bin/sh\nexit 0\n").expect("write poly");
        {
            use std::os::unix::fs::PermissionsExt as _;
            std::fs::set_permissions(&installed, std::fs::Permissions::from_mode(0o755)).expect("chmod");
        }

        let output = run_pre_commit_shim(&dir.path().join("hooks"), &bin, &home);
        let stderr = String::from_utf8_lossy(&output.stderr);

        assert_eq!(output.status.code(), Some(1), "hook must fail closed:\n{stderr}");
        assert!(
            stderr.contains("not on the PATH this hook sees"),
            "expected the off-PATH message:\n{stderr}"
        );
        assert!(
            stderr.contains(installed.to_str().expect("utf-8 path")),
            "expected the install path as evidence:\n{stderr}"
        );
    }

    #[cfg(unix)]
    #[test]
    fn shim_execs_poly_and_forwards_hook_arguments() {
        let dir = TempDir::new().expect("tempdir");
        let bin = dir.path().join("bin");
        let home = dir.path().join("home");
        std::fs::create_dir_all(&bin).expect("mkdir");
        std::fs::create_dir_all(&home).expect("mkdir");

        let fake_poly = bin.join("poly");
        std::fs::write(&fake_poly, "#!/bin/sh\nprintf 'ARGS:%s\\n' \"$*\"\n").expect("write fake poly");
        {
            use std::os::unix::fs::PermissionsExt as _;
            std::fs::set_permissions(&fake_poly, std::fs::Permissions::from_mode(0o755)).expect("chmod");
        }

        install(&dir.path().join("hooks"), &[HookType::PreCommit], false).expect("install");
        let output = std::process::Command::new("/bin/sh")
            .arg(dir.path().join("hooks/pre-commit"))
            .arg("extra-arg")
            .env_clear()
            .env("PATH", &bin)
            .env("HOME", &home)
            .output()
            .expect("run shim");

        assert_eq!(output.status.code(), Some(0));
        assert_eq!(
            String::from_utf8_lossy(&output.stdout),
            "ARGS:hooks hook-impl --hook-type=pre-commit -- extra-arg\n"
        );
    }

    #[test]
    fn uninstall_leaves_unmanaged_hooks_untouched() {
        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");
        std::fs::create_dir_all(&hooks).expect("mkdir");

        let pre_commit = hooks.join("pre-commit");
        let original = "#!/bin/sh\necho not poly\n";
        std::fs::write(&pre_commit, original).expect("write");

        let removed = uninstall(&hooks, &[HookType::PreCommit]).expect("uninstall");
        assert!(removed.is_empty());
        assert_eq!(std::fs::read_to_string(&pre_commit).expect("read"), original);
    }
}
