//! Install and uninstall poly's git-hook shims.
//!
//! Ported (and retargeted to `poly`) from `polyhooks/src/cli/install.rs`. Each
//! installed `.git/hooks/<hook-type>` script is a tiny POSIX-shell shim that
//! execs the running `poly` binary as:
//!
//! ```sh
//! exec "$POLY" hooks hook-impl --hook-type=<hook-type> -- "$@"
//! ```
//!
//! The store/workspace/provisioning machinery, the `core.hooksPath` refusal
//! logic, legacy-hook *execution* chaining (migration mode), and
//! `init_template_dir` are intentionally **not** ported — they are out of scope
//! for the crate-side shims (and `polyhooks` is removed in B4). The caller
//! (`poly-cli`) resolves the hooks directory via [`crate::git::get_git_hooks_dir`]
//! and passes it in, together with the path to the running `poly` binary.

use std::io::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::ValueEnum as _;

use crate::stage::HookType;

/// Marker embedded in every poly-generated shim so install/uninstall can tell a
/// poly shim apart from a user's own hook. Bump the suffix if the template
/// changes in a way that requires re-installation.
const HOOK_MARKER: &str = "poly-hook-shim:v1";

/// Shell template for an installed git-hook shim.
///
/// `[POLY_PATH]` is replaced with the quoted absolute path to the running
/// `poly` binary; `[HOOK_TYPE]` with the kebab-case hook name. `exec` replaces
/// the shell process, so the hook's stdin (used by `pre-push`) and arguments
/// are forwarded transparently.
static HOOK_TMPL: &str = r#"#!/bin/sh
# File generated by poly. Do not edit.
# poly-hook-shim:v1

POLY=[POLY_PATH]

# If the recorded poly path is not executable, fall back to PATH.
if [ ! -x "$POLY" ]; then
    POLY="poly"
fi

exec "$POLY" hooks hook-impl --hook-type=[HOOK_TYPE] -- "$@"
"#;

/// Default file mode for an installed shim (owner rwx, group/other rx).
#[cfg(unix)]
const HOOK_MODE: u32 = 0o755;

/// Resolve the set of hook types to act on: an explicit list, or all ten
/// git-triggered hook types when `requested` is empty.
fn resolve_types(requested: &[HookType]) -> Vec<HookType> {
    if requested.is_empty() {
        HookType::value_variants().to_vec()
    } else {
        requested.to_vec()
    }
}

/// Path of the `.legacy` sibling for a given hook name.
fn legacy_path(hooks_dir: &Path, hook_type: HookType) -> PathBuf {
    hooks_dir.join(format!("{}.legacy", hook_type.as_ref()))
}

/// Single-quote a string for safe interpolation into a POSIX `sh` script.
///
/// Single quotes disable every shell metacharacter (`$`, backticks, `$()`, …);
/// an embedded single quote is emitted via the standard `'\''` break-out. A
/// double-quoted wrap would still expand `$VAR`/`` `cmd` `` in a poly binary
/// path like `/home/$USER/bin/poly`, so single quotes are required here.
fn shell_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// Render the shim script for `hook_type`, pointing at `poly_bin`.
fn render_shim(poly_bin: &Path, hook_type: HookType) -> String {
    HOOK_TMPL
        .replace("[POLY_PATH]", &shell_single_quote(&poly_bin.display().to_string()))
        .replace("[HOOK_TYPE]", hook_type.as_ref())
}

/// Whether `path` is a shim that poly generated (by marker content).
///
/// A missing file is treated as "not ours" rather than an error.
fn is_our_shim(path: &Path) -> Result<bool> {
    match std::fs::read_to_string(path) {
        Ok(content) => Ok(content.contains(HOOK_MARKER)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(err) => Err(err.into()),
    }
}

/// Write `script` to `path` atomically (write a sibling tmp file, set the exec
/// bit on it, then rename into place), so an interrupted install never leaves a
/// half-written, unmanaged hook behind.
fn write_shim(path: &Path, script: &str) -> Result<()> {
    let tmp = path.with_extension("poly-tmp");
    {
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open(&tmp)
            .with_context(|| format!("failed to open hook shim tmp `{}`", tmp.display()))?;
        file.write_all(script.as_bytes())
            .with_context(|| format!("failed to write hook shim tmp `{}`", tmp.display()))?;
    }

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let mut perms = tmp
            .metadata()
            .with_context(|| format!("failed to read permissions for `{}`", tmp.display()))?
            .permissions();
        perms.set_mode(HOOK_MODE);
        std::fs::set_permissions(&tmp, perms)
            .with_context(|| format!("failed to set exec bit on `{}`", tmp.display()))?;
    }

    std::fs::rename(&tmp, path).with_context(|| format!("failed to install hook shim `{}`", path.display()))?;
    Ok(())
}

/// Install a single hook shim, preserving any pre-existing foreign hook.
fn install_one(hooks_dir: &Path, poly_bin: &Path, hook_type: HookType, overwrite: bool) -> Result<PathBuf> {
    let hook_path = hooks_dir.join(hook_type.as_ref());
    let legacy = legacy_path(hooks_dir, hook_type);

    if hook_path.try_exists()? {
        if overwrite {
            // Discard any preserved legacy hook when explicitly overwriting.
            if legacy.try_exists()? {
                std::fs::remove_file(&legacy).with_context(|| format!("failed to remove `{}`", legacy.display()))?;
            }
        } else if !is_our_shim(&hook_path)? {
            // A non-poly hook is already installed: move it aside so we can
            // restore it on uninstall. Refuse to clobber an existing `.legacy`
            // backup rather than silently destroying it.
            if legacy.try_exists()? {
                anyhow::bail!(
                    "cannot preserve existing hook `{}`: `{}` already exists; \
                     remove or rename it, or re-run with overwrite",
                    hook_path.display(),
                    legacy.display()
                );
            }
            std::fs::rename(&hook_path, &legacy).with_context(|| {
                format!(
                    "failed to preserve existing hook `{}` as `{}`",
                    hook_path.display(),
                    legacy.display()
                )
            })?;
        }
    }

    write_shim(&hook_path, &render_shim(poly_bin, hook_type))?;
    Ok(hook_path)
}

/// Install poly git-hook shims into `hooks_dir`.
///
/// When `hook_types` is empty, all ten git-triggered hook types are installed.
/// `poly_bin` is the path recorded in each shim (typically
/// `std::env::current_exe()`). A pre-existing non-poly hook is preserved as
/// `<name>.legacy` (unless `overwrite` is set, which discards it). Returns the
/// paths of the shims that were written.
pub fn install(hooks_dir: &Path, poly_bin: &Path, hook_types: &[HookType], overwrite: bool) -> Result<Vec<PathBuf>> {
    std::fs::create_dir_all(hooks_dir)
        .with_context(|| format!("failed to create hooks dir `{}`", hooks_dir.display()))?;

    let types = resolve_types(hook_types);
    let mut installed = Vec::with_capacity(types.len());
    for hook_type in types {
        installed.push(install_one(hooks_dir, poly_bin, hook_type, overwrite)?);
    }
    Ok(installed)
}

/// Uninstall poly git-hook shims from `hooks_dir`, restoring any preserved
/// `<name>.legacy` hook.
///
/// When `hook_types` is empty, all ten git-triggered hook types are considered.
/// Hooks not managed by poly are left untouched. Returns the paths of the shims
/// that were removed.
pub fn uninstall(hooks_dir: &Path, hook_types: &[HookType]) -> Result<Vec<PathBuf>> {
    let types = resolve_types(hook_types);
    let mut removed = Vec::new();

    for hook_type in types {
        let hook_path = hooks_dir.join(hook_type.as_ref());
        let legacy = legacy_path(hooks_dir, hook_type);

        // A poly shim that somehow landed in the legacy slot is stale; drop it.
        if is_our_shim(&legacy)? {
            std::fs::remove_file(&legacy).with_context(|| format!("failed to remove `{}`", legacy.display()))?;
        }

        if !is_our_shim(&hook_path)? {
            continue;
        }

        std::fs::remove_file(&hook_path).with_context(|| format!("failed to remove `{}`", hook_path.display()))?;
        removed.push(hook_path.clone());

        // Restore a previously preserved foreign hook, if any.
        if legacy.try_exists()? {
            std::fs::rename(&legacy, &hook_path).with_context(|| {
                format!(
                    "failed to restore legacy hook `{}` to `{}`",
                    legacy.display(),
                    hook_path.display()
                )
            })?;
        }
    }

    Ok(removed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    const FAKE_POLY: &str = "/usr/bin/poly";

    #[test]
    fn install_writes_shim_with_exec_line() {
        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");

        let written = install(&hooks, Path::new(FAKE_POLY), &[HookType::PreCommit], false).expect("install");

        let shim = hooks.join("pre-commit");
        assert_eq!(written, vec![shim.clone()]);

        let content = std::fs::read_to_string(&shim).expect("read shim");
        assert!(
            content.contains("hooks hook-impl --hook-type=pre-commit -- \"$@\""),
            "shim missing exec line:\n{content}"
        );
        assert!(content.contains(HOOK_MARKER));
        assert!(content.contains(FAKE_POLY));
    }

    #[cfg(unix)]
    #[test]
    fn install_sets_executable_bit() {
        use std::os::unix::fs::PermissionsExt as _;

        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");
        install(&hooks, Path::new(FAKE_POLY), &[HookType::PreCommit], false).expect("install");

        let mode = std::fs::metadata(hooks.join("pre-commit"))
            .expect("metadata")
            .permissions()
            .mode();
        assert_eq!(mode & 0o111, 0o111, "shim is not executable: {mode:o}");
    }

    #[test]
    fn install_with_empty_list_writes_all_ten_shims() {
        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");
        let written = install(&hooks, Path::new(FAKE_POLY), &[], false).expect("install");
        assert_eq!(written.len(), 10);
    }

    #[test]
    fn install_preserves_foreign_hook_and_uninstall_restores_it() {
        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");
        std::fs::create_dir_all(&hooks).expect("mkdir");

        let pre_commit = hooks.join("pre-commit");
        let original = "#!/bin/sh\necho legacy hook\n";
        std::fs::write(&pre_commit, original).expect("write foreign hook");

        install(&hooks, Path::new(FAKE_POLY), &[HookType::PreCommit], false).expect("install");

        let legacy = hooks.join("pre-commit.legacy");
        assert!(legacy.exists(), "foreign hook was not preserved");
        assert!(
            std::fs::read_to_string(&pre_commit)
                .expect("read shim")
                .contains(HOOK_MARKER),
            "shim was not installed over the foreign hook"
        );

        let removed = uninstall(&hooks, &[HookType::PreCommit]).expect("uninstall");
        assert_eq!(removed, vec![pre_commit.clone()]);
        assert!(!legacy.exists(), "legacy hook was not restored");
        assert_eq!(std::fs::read_to_string(&pre_commit).expect("read restored"), original);
    }

    #[test]
    fn uninstall_leaves_unmanaged_hooks_untouched() {
        let dir = TempDir::new().expect("tempdir");
        let hooks = dir.path().join("hooks");
        std::fs::create_dir_all(&hooks).expect("mkdir");

        let pre_commit = hooks.join("pre-commit");
        let original = "#!/bin/sh\necho not poly\n";
        std::fs::write(&pre_commit, original).expect("write");

        let removed = uninstall(&hooks, &[HookType::PreCommit]).expect("uninstall");
        assert!(removed.is_empty());
        assert_eq!(std::fs::read_to_string(&pre_commit).expect("read"), original);
    }
}
