
[languages.elixir]
reference = "mix format"
extensions = ["ex", "exs"]

[languages.shell]
reference = "shfmt -i 2"
extensions = ["sh", "bash"]

[languages.ruby]
reference = "standardrb --fix"
extensions = ["rb"]

[languages.php]
reference = "laravel/pint"
extensions = ["php"]

[languages.java]
reference = "palantir-java-format"
extensions = ["java"]

[languages.kotlin]
reference = "ktfmt"
extensions = ["kt", "kts"]

[languages.swift]
reference = "swift-format"
extensions = ["swift"]

[languages.dart]
reference = "dart format"
extensions = ["dart"]

[languages.csharp]
reference = "csharpier"
extensions = ["cs"]

[languages.zig]
reference = "zig fmt"
extensions = ["zig"]
