//! rumdl backend — Markdown lint and auto-format.
//!
//! Wraps [`rumdl_lib`](https://crates.io/crates/rumdl) in-process — no subprocess, no system
//! dependency. Capabilities: lint (standard markdownlint rules; rumdl-proprietary stylistic
//! extensions off by default — see the `DEFAULT_DISABLED_RULES` constant) + format (apply all
//! auto-fixable rules iteratively until convergence).
//!
//! Config layering: rumdl defaults → opinionated override (line-length 120) → user
//! `[lint.markdown.rumdl]` / `[fmt.markdown.rumdl]` table in `poly.toml`.
//!
//! Rule selection accepts the canonical vocabulary (ADR 0016): `select` /
//! `extend_select` map onto rumdl's `enable`, and `ignore` maps onto `disable`.
//! The native `enable` / `disable` keys remain accepted as aliases and are
//! unioned with the canonical keys.

use std::collections::HashSet;
use std::sync::{Arc, LazyLock};

use regex::Regex;
use rumdl_lib::{
    LintContext,
    config::{Config as RumdlConfig, MarkdownFlavor},
    fix_coordinator::FixCoordinator,
    rule::{FixCapability, LintError, LintResult, LintWarning, Rule, RuleCategory, Severity as RumdlSeverity},
    rules::{MD020NoMissingSpaceClosedAtx, all_rules, filter_rules},
    types::LineLength,
};

use super::rule_config::{RuleSelection, string_list, union_codes, warn_and_skip_blank};
use super::template::{GO_TEMPLATE_SKIP, contains_go_template};
use crate::config::EngineConfig;
use crate::engine::{Capabilities, Diagnostic, Edit, Engine, FormatOutput, Severity, SourceFile, Span};
use crate::language::Language;

/// rumdl Markdown lint + format backend.
pub struct RumdlEngine;

/// Embedded crate version so the cache key changes whenever rumdl output could change.
/// The `+defaults5…` suffix marks the opinionated rule policy below: the
/// default-disabled proprietary rules **and** the lint-mode suppression of the
/// `Whitespace` (formatting) category, plus MDX-flavor routing, the MDX-only
/// default-disabled rules (see [`MDX_DEFAULT_DISABLED_RULES`]), the
/// Go/Helm-template skip, and the MD020 guard ([`GuardedMd020`]). Bump the
/// suffix whenever any of these change so stale cached diagnostics are
/// invalidated.
const RUMDL_VERSION: &str = "0.2.54+defaults5-mdx-rules-tmplskip-md020guard";

/// rumdl-proprietary stylistic rules disabled by default.
///
/// These extend beyond the standard markdownlint set (which stops at MD059) and
/// are purely stylistic — table-cell alignment (MD060), heading capitalization
/// (MD063), frontmatter key sort (MD072), heading-anchor collisions (MD080), and
/// empty sections (MD082). Per the project's defaults policy ("purely stylistic
/// rules: pick one convention or turn the rule off — never bikeshed"), they are
/// off by default. A user can re-enable any of them via an `enable` list in the
/// `[lint.markdown.rumdl]` table of `poly.toml`.
const DEFAULT_DISABLED_RULES: &[&str] = &["MD060", "MD063", "MD072", "MD080", "MD082"];

/// Rules disabled by default **only for MDX** (`.mdx`) files.
///
/// MDX is Markdown plus JSX elements and ESM `import`/`export`, so a handful of
/// standard rules fire constantly on legitimate content and are pure noise there:
///
/// - **MD033** (no inline HTML) — JSX elements (`<div>`, `<Note>`, `<code>`, …) are
///   the whole point of MDX; flagging them is nonsensical.
/// - **MD036** (emphasis used instead of a heading) — doc-site MDX routinely uses
///   emphasized lead-ins for visual styling rather than as headings.
/// - **MD041** (first line must be a top-level heading) — MDX files open with
///   `import`/`export` statements or frontmatter, never an H1.
/// - **MD051** (link fragments must exist) — heading anchors are generated by the
///   MDX toolchain (and by JSX/custom components), so rumdl's anchor computation
///   produces false "anchor does not exist" errors.
///
/// These are layered on top of [`DEFAULT_DISABLED_RULES`] and, like it, a user can
/// re-enable any of them via an `enable` list in `[lint.markdown.rumdl]`.
const MDX_DEFAULT_DISABLED_RULES: &[&str] = &["MD033", "MD036", "MD041", "MD051"];

static LANGUAGES: &[Language] = &[Language::Markdown, Language::Mdx];

impl Engine for RumdlEngine {
    fn name(&self) -> &'static str {
        "rumdl"
    }

    fn languages(&self) -> &'static [Language] {
        LANGUAGES
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            lint: true,
            format: true,
            fix: true,
        }
    }

    fn version(&self) -> &str {
        RUMDL_VERSION
    }

    fn skip_reason(&self, src: &SourceFile) -> Option<&'static str> {
        contains_go_template(&src.content).then_some(GO_TEMPLATE_SKIP)
    }

    fn lint(&self, src: &SourceFile, cfg: &EngineConfig) -> anyhow::Result<Vec<Diagnostic>> {
        if contains_go_template(&src.content) {
            return Ok(Vec::new());
        }
        let rumdl_cfg = build_rumdl_config(cfg, &src.language);
        let rules = guarded_rules(&rumdl_cfg, &src.content);
        let flavor = rumdl_cfg.markdown_flavor();
        let format_owned = format_owned_rules(&rules);
        rumdl_lib::lint(
            &src.content,
            &rules,
            false,
            flavor,
            Some(src.path.clone()),
            Some(&rumdl_cfg),
        )
        .map(|warnings| {
            warnings
                .iter()
                .filter(|w| !is_format_owned(w, &format_owned))
                .map(|w| map_warning(w, "rumdl"))
                .collect()
        })
        .map_err(|e| anyhow::anyhow!("rumdl lint: {e}"))
    }

    fn format(&self, src: &SourceFile, cfg: &EngineConfig) -> anyhow::Result<FormatOutput> {
        if contains_go_template(&src.content) {
            return Ok(FormatOutput::Unchanged);
        }
        let rumdl_cfg = build_rumdl_config(cfg, &src.language);
        let rules = guarded_rules(&rumdl_cfg, &src.content);
        let coordinator = FixCoordinator::default();
        let mut content = src.content.to_string();
        coordinator
            .apply_fixes_iterative(&rules, &[], &mut content, &rumdl_cfg, 10, Some(&src.path))
            .map_err(|e| anyhow::anyhow!("rumdl format: {e}"))?;
        if content == *src.content {
            Ok(FormatOutput::Unchanged)
        } else {
            Ok(FormatOutput::Formatted(content))
        }
    }
}

/// Build a [`RumdlConfig`] from the resolved engine config, applying the opinionated override
/// layer (line-length 120) before user options. `language` selects rumdl's Markdown
/// flavor: [`Language::Mdx`] enables the MDX flavor (JSX + ESM aware) so `.mdx`
/// files are parsed correctly.
fn build_rumdl_config(cfg: &EngineConfig, language: &Language) -> RumdlConfig {
    let mut config = RumdlConfig::default();

    if *language == Language::Mdx {
        config.global.flavor = MarkdownFlavor::MDX;
    }

    let line_length = cfg
        .options
        .get("line_length")
        .and_then(toml::Value::as_integer)
        .map(|v| v as usize)
        .unwrap_or(cfg.globals.line_length);
    config.global.line_length = LineLength::new(line_length);

    let selection = RuleSelection::from_options(cfg);

    let user_enable = warn_and_skip_blank(
        union_codes(
            string_list(cfg, "enable"),
            selection.select.into_iter().chain(selection.extend_select),
        ),
        "rumdl",
    );
    let user_disable = warn_and_skip_blank(union_codes(string_list(cfg, "disable"), selection.ignore), "rumdl");

    let default_disabled = DEFAULT_DISABLED_RULES.iter().chain(
        (*language == Language::Mdx)
            .then_some(MDX_DEFAULT_DISABLED_RULES)
            .into_iter()
            .flatten(),
    );
    let mut disable: Vec<String> = default_disabled
        .filter(|rule| !user_enable.iter().any(|e| e.eq_ignore_ascii_case(rule)))
        .map(|rule| (*rule).to_owned())
        .collect();
    disable.extend(user_disable);

    config.global.disable = disable;
    config.global.enable = user_enable;
    config
}

/// Rule code of rumdl's "no space inside closed ATX heading" rule.
const MD020: &str = "MD020";

/// Matches an ATX heading line whose *text* ends in `#`, such as `### C#`.
///
/// Mirrors rumdl's own `CLOSED_ATX_NO_SPACE_END_PATTERN`
/// (`rules/md020_no_missing_space_closed_atx.rs`) minus its capture groups: an
/// opening hash run, a space, content whose last character is not `#`,
/// whitespace or a backslash, then a trailing hash run and an optional
/// `{#custom-id}`.
///
/// CommonMark §4.2 requires a heading's closing sequence of `#`s to be preceded
/// by whitespace, so `### C#` has *no* closing sequence — it is an ordinary open
/// ATX heading whose content is `C#`. MD020 reads the trailing `#` as a
/// malformed closing sequence anyway and rewrites the line to `### C #`, which
/// MD003 then normalises to `### C`, silently dropping the `#` from the rendered
/// heading. [`GuardedMd020`] suppresses that branch.
static HEADING_TEXT_ENDS_IN_HASH: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^\s*#+\s.*?[^#\s\\]#+\s*(?:\{#[^}]+\})?\s*$").expect("valid regex"));

/// rumdl's MD020 with its CommonMark-invalid branch neutralised.
///
/// MD020's other branches are legitimate and delegate untouched: `#Foo#` and
/// `#Foo #` lack the space *after* the opening hashes, so they are not headings
/// at all and rewriting them is correct. Only the "missing space before the
/// closing hashes" branch is suppressed, because the construct it reports
/// (`### C#`, `## F#`) is valid CommonMark and applying its fix corrupts the
/// heading text.
///
/// A line is protected only when the author actually wrote it — it must match
/// [`HEADING_TEXT_ENDS_IN_HASH`] *and* appear verbatim in the original document.
/// Formatting is iterative, so `##Foo##` becomes `## Foo##` mid-run once MD018
/// has inserted the opening space; that intermediate line was never authored and
/// stays fixable, which keeps `##Foo##` → `## Foo ##` intact.
///
/// [`guarded_rules`] swaps this in for every lint and format run. Two narrow
/// cases still escape the guard, both waiting on the upstream fix:
///
/// - A heading written *without* the mandatory space after the opening hashes
///   (`###C#`) is not a heading at all, so MD018 rewrites it to `### C#` first;
///   that line was never authored and is indistinguishable from a malformed
///   closed heading, so MD020 still reaches it.
/// - A document carrying an inline `rumdl-configure-file` override for MD020
///   makes rumdl's fix coordinator recreate the rule straight from its registry.
#[derive(Clone)]
struct GuardedMd020 {
    inner: MD020NoMissingSpaceClosedAtx,
    /// The document as the author wrote it, before any fix pass.
    original: Arc<str>,
}

impl GuardedMd020 {
    fn new(original: Arc<str>) -> Self {
        Self {
            inner: MD020NoMissingSpaceClosedAtx::new(),
            original,
        }
    }

    /// Whether `line` is a heading MD020 must not touch — see
    /// [`HEADING_TEXT_ENDS_IN_HASH`]. Accepts a line with or without its terminator.
    fn is_guarded(&self, line: &str) -> bool {
        let line = line.trim_end_matches(['\r', '\n']);
        HEADING_TEXT_ENDS_IN_HASH.is_match(line) && self.original.lines().any(|authored| authored == line)
    }
}

impl Rule for GuardedMd020 {
    fn name(&self) -> &'static str {
        self.inner.name()
    }

    fn description(&self) -> &'static str {
        self.inner.description()
    }

    fn check(&self, ctx: &LintContext) -> LintResult {
        let mut warnings = self.inner.check(ctx)?;
        warnings.retain(|warning| !nth_line(ctx.content, warning.line).is_some_and(|line| self.is_guarded(line)));
        Ok(warnings)
    }

    fn fix(&self, ctx: &LintContext) -> Result<String, LintError> {
        let fixed = self.inner.fix(ctx)?;
        Ok(self.restore_guarded_headings(ctx.content, fixed))
    }

    fn should_skip(&self, ctx: &LintContext) -> bool {
        self.inner.should_skip(ctx)
    }

    fn category(&self) -> RuleCategory {
        self.inner.category()
    }

    fn fix_capability(&self) -> FixCapability {
        self.inner.fix_capability()
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self.inner.as_any()
    }
}

/// The 1-indexed `line_number`th line of `content`, without its terminator.
fn nth_line(content: &str, line_number: usize) -> Option<&str> {
    content.lines().nth(line_number.checked_sub(1)?)
}

impl GuardedMd020 {
    /// Put every guarded heading back the way the author wrote it.
    ///
    /// [`GuardedMd020::check`] already hides the guarded warnings, so the
    /// coordinator only reaches `fix` when the document *also* holds a genuine
    /// MD020 violation. MD020 rewrites lines in place, so the fixed content keeps
    /// one line per input line; if that ever stops holding the whole fix is
    /// dropped rather than splicing mismatched lines together.
    fn restore_guarded_headings(&self, before_fix: &str, fixed: String) -> String {
        if !before_fix.split_inclusive('\n').any(|line| self.is_guarded(line)) {
            return fixed;
        }
        let before_lines: Vec<&str> = before_fix.split_inclusive('\n').collect();
        let fixed_lines: Vec<&str> = fixed.split_inclusive('\n').collect();
        if before_lines.len() != fixed_lines.len() {
            return before_fix.to_owned();
        }
        before_lines
            .into_iter()
            .zip(fixed_lines)
            .map(|(before_line, fixed_line)| {
                if self.is_guarded(before_line) {
                    before_line
                } else {
                    fixed_line
                }
            })
            .collect()
    }
}

/// Resolve the active rule set, with [`GuardedMd020`] standing in for MD020.
fn guarded_rules(config: &RumdlConfig, original: &Arc<str>) -> Vec<Box<dyn Rule>> {
    filter_rules(&all_rules(config), &config.global)
        .into_iter()
        .map(|rule| {
            if rule.name() == MD020 {
                Box::new(GuardedMd020::new(Arc::clone(original))) as Box<dyn Rule>
            } else {
                rule
            }
        })
        .collect()
}

/// The set of rule codes (e.g. `"MD013"`) that belong to rumdl's `Whitespace`
/// category — the formatting rules `poly fmt` owns. Built from the active rule
/// set so it tracks the tool's own categorisation rather than a hardcoded list.
fn format_owned_rules(rules: &[Box<dyn Rule>]) -> HashSet<&'static str> {
    rules
        .iter()
        .filter(|rule| rule.category() == RuleCategory::Whitespace)
        .map(|rule| rule.name())
        .collect()
}

/// Whether a warning belongs to a formatting-owned rule and must not surface in
/// `poly lint`. A warning with no rule name is never suppressed (it cannot be
/// attributed to a formatting rule).
fn is_format_owned(warning: &LintWarning, format_owned: &HashSet<&'static str>) -> bool {
    warning
        .rule_name
        .as_deref()
        .is_some_and(|name| format_owned.contains(name))
}

/// Map a rumdl [`LintWarning`] to the shared [`Diagnostic`] type.
fn map_warning(w: &LintWarning, engine: &str) -> Diagnostic {
    let severity = match w.severity {
        RumdlSeverity::Error => Severity::Error,
        RumdlSeverity::Warning => Severity::Warning,
        RumdlSeverity::Info => Severity::Info,
    };
    let fix: Vec<Edit> = w
        .fix
        .as_ref()
        .map(|f| Edit {
            start_byte: f.range.start,
            end_byte: f.range.end,
            replacement: f.replacement.clone(),
        })
        .into_iter()
        .collect();
    Diagnostic {
        engine: engine.to_owned(),
        code: w.rule_name.clone(),
        severity,
        title: w.message.clone(),
        description: None,
        url: None,
        span: Some(Span {
            start_line: w.line as u32,
            start_col: w.column as u32,
            end_line: w.end_line as u32,
            end_col: w.end_column as u32,
        }),
        fix,
        metadata: Default::default(),
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::config::{EngineConfig, GlobalDefaults};

    fn default_cfg() -> EngineConfig {
        EngineConfig {
            globals: GlobalDefaults::default(),
            indent_width: 4,
            options: toml::Table::new(),
        }
    }

    fn source(content: &str) -> SourceFile {
        SourceFile {
            path: PathBuf::from("test.md"),
            language: Language::Markdown,
            content: content.into(),
        }
    }

    fn mdx_source(content: &str) -> SourceFile {
        SourceFile {
            path: PathBuf::from("test.mdx"),
            language: Language::Mdx,
            content: content.into(),
        }
    }

    #[test]
    fn mdx_language_selects_mdx_flavor() {
        let cfg = default_cfg();
        assert_eq!(
            build_rumdl_config(&cfg, &Language::Mdx).markdown_flavor(),
            MarkdownFlavor::MDX
        );
        assert_ne!(
            build_rumdl_config(&cfg, &Language::Markdown).markdown_flavor(),
            MarkdownFlavor::MDX
        );
    }

    #[test]
    fn mdx_file_is_linted() {
        let engine = RumdlEngine;
        let src = mdx_source("#Bad Heading\n\nContent.\n");
        let diags = engine.lint(&src, &default_cfg()).expect("lint succeeded");
        let codes: Vec<_> = diags.iter().filter_map(|d| d.code.as_deref()).collect();
        assert!(codes.contains(&"MD018"), "mdx file should be linted, got {codes:?}");
    }

    #[test]
    fn mdx_disables_inline_html_and_anchor_rules() {
        let engine = RumdlEngine;
        // Inline JSX/HTML (MD033) plus an emphasis-as-heading lead-in (MD036) — both
        // legitimate MDX and both silenced by the MDX default-disabled set.
        let src =
            mdx_source("import Foo from './foo'\n\n# Heading\n\n<div class=\"chip\">hi</div>\n\n*Styled lead-in*\n");
        let diags = engine.lint(&src, &default_cfg()).expect("lint succeeded");
        let codes: Vec<_> = diags.iter().filter_map(|d| d.code.as_deref()).collect();
        assert!(!codes.contains(&"MD033"), "MD033 must be off for mdx, got {codes:?}");
        assert!(!codes.contains(&"MD036"), "MD036 must be off for mdx, got {codes:?}");
    }

    #[test]
    fn markdown_keeps_inline_html_rule() {
        // The MDX default-disabled set must NOT bleed into plain Markdown.
        let engine = RumdlEngine;
        let src = source("# Heading\n\n<div class=\"chip\">hi</div>\n");
        let diags = engine.lint(&src, &default_cfg()).expect("lint succeeded");
        let codes: Vec<_> = diags.iter().filter_map(|d| d.code.as_deref()).collect();
        assert!(
            codes.contains(&"MD033"),
            "MD033 must stay on for plain markdown, got {codes:?}"
        );
    }

    #[test]
    fn mdx_disabled_rule_can_be_reenabled() {
        // A user `enable` list wins over the MDX default-disabled set.
        let mut cfg = default_cfg();
        cfg.options
            .insert("enable".into(), toml::Value::Array(vec!["MD033".into()]));
        let engine = RumdlEngine;
        let src = mdx_source("# Heading\n\n<div class=\"chip\">hi</div>\n");
        let diags = engine.lint(&src, &cfg).expect("lint succeeded");
        let codes: Vec<_> = diags.iter().filter_map(|d| d.code.as_deref()).collect();
        assert!(
            codes.contains(&"MD033"),
            "explicit enable must re-enable MD033, got {codes:?}"
        );
    }

    #[test]
    fn helm_templated_markdown_is_skipped() {
        let engine = RumdlEngine;
        let src = source("#Bad Heading\n\n{{- if .Values.enabled }}\nContent.\n{{- end }}\n");
        assert!(
            engine.lint(&src, &default_cfg()).expect("lint succeeded").is_empty(),
            "templated markdown must be skipped by lint"
        );
        assert!(
            matches!(
                engine.format(&src, &default_cfg()).expect("format succeeded"),
                FormatOutput::Unchanged
            ),
            "templated markdown must be skipped by format"
        );
    }

    #[test]
    fn lint_returns_diagnostics_for_invalid_heading() {
        let engine = RumdlEngine;
        let src = source("#Bad Heading\n\nContent.\n");
        let cfg = default_cfg();
        let diags = engine.lint(&src, &cfg).expect("lint succeeded");
        let codes: Vec<_> = diags.iter().filter_map(|d| d.code.as_deref()).collect();
        assert!(codes.contains(&"MD018"), "expected MD018 in {codes:?}");
    }

    #[test]
    fn lint_suppresses_whitespace_category_rules() {
        let engine = RumdlEngine;
        let long = "x".repeat(200);
        let src = source(&format!("# Heading\n\n{long}\n"));
        let cfg = default_cfg();
        let diags = engine.lint(&src, &cfg).expect("lint succeeded");
        let codes: Vec<_> = diags.iter().filter_map(|d| d.code.as_deref()).collect();
        assert!(
            !codes.contains(&"MD013"),
            "MD013 (Whitespace category) must be suppressed in lint, got {codes:?}"
        );
    }

    #[test]
    fn lint_keeps_structural_rules() {
        let engine = RumdlEngine;
        let src = source("#Bad Heading\n\nContent.\n");
        let cfg = default_cfg();
        let diags = engine.lint(&src, &cfg).expect("lint succeeded");
        let codes: Vec<_> = diags.iter().filter_map(|d| d.code.as_deref()).collect();
        assert!(codes.contains(&"MD018"), "structural rule must survive, got {codes:?}");
    }

    #[test]
    fn format_removes_trailing_whitespace() {
        let engine = RumdlEngine;
        let src = source("# Heading\n\nLine with trailing spaces   \n\nContent.\n");
        let cfg = default_cfg();
        match engine.format(&src, &cfg).expect("format succeeded") {
            FormatOutput::Formatted(out) => {
                assert!(
                    !out.contains("   \n"),
                    "trailing whitespace should be removed, got:\n{out}"
                );
            }
            FormatOutput::Unchanged => panic!("expected Formatted, got Unchanged"),
        }
    }

    #[test]
    fn guard_protects_only_authored_headings_ending_in_hash() {
        let original: Arc<str> = "### C#\n## F#\n### Foo ###\n### Foo #\n### C# and more\n### C\\#\n".into();
        let guard = GuardedMd020::new(Arc::clone(&original));

        for line in ["### C#", "## F#", "### C#\n"] {
            assert!(guard.is_guarded(line), "{line:?} must be protected from MD020");
        }
        for line in [
            "### Foo ###",     // genuine closed heading — nothing missing
            "### Foo #",       // genuine closed heading with a one-hash closer
            "### C# and more", // trailing text, not a hash run
            "### C\\#",        // already escaped
            "##Foo##",         // missing the opening space: a real MD020 violation
            "## Foo##",        // never authored — an intermediate state of `##Foo##`
        ] {
            assert!(!guard.is_guarded(line), "{line:?} must stay fixable");
        }
    }

    /// Pins the one residual gap documented on [`GuardedMd020`]: `###C#` is not a
    /// heading (no space after the opening hashes), MD018 rewrites it to `### C#`
    /// mid-run, and that synthesised line is still MD020's to mangle. Update this
    /// test when the upstream MD020 fix lands and the guard can be dropped.
    #[test]
    fn known_residual_heading_missing_opening_space_still_loses_trailing_hash() {
        let engine = RumdlEngine;
        let src = source("###C#\n");
        match engine.format(&src, &default_cfg()).expect("format succeeded") {
            FormatOutput::Formatted(out) => assert_eq!(out, "### C #\n"),
            FormatOutput::Unchanged => panic!("expected MD018 to rewrite `###C#`"),
        }
    }

    #[test]
    fn heading_text_ending_in_hash_is_not_rewritten_by_format() {
        let engine = RumdlEngine;
        let src = source("# Languages\n\n## Overview\n\n### C#\n\nText.\n");
        assert!(
            matches!(
                engine.format(&src, &default_cfg()).expect("format succeeded"),
                FormatOutput::Unchanged
            ),
            "`### C#` must survive formatting untouched"
        );
    }

    #[test]
    fn format_already_clean_is_unchanged() {
        let engine = RumdlEngine;
        let src = source("# Heading\n\nClean line.\n");
        let cfg = default_cfg();
        assert!(
            matches!(
                engine.format(&src, &cfg).expect("format succeeded"),
                FormatOutput::Unchanged
            ),
            "already-clean file should be Unchanged"
        );
    }
}
