#!/usr/bin/env bash
set -euo pipefail

# update-homebrew-formula.sh <version> [release-repo]

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
  echo "Usage: $0 <version> [release-repo]" >&2
  exit 1
fi

VERSION="$1"
RELEASE_REPO="${2:-Goldziher/poly}"
TAG="v${VERSION}"
BASE_URL="https://github.com/${RELEASE_REPO}/releases/download/${TAG}"

SUMS="$(curl -fsSL "${BASE_URL}/sha256sums.txt")"

sha_for() {
  echo "$SUMS" | awk -v f="$1" '$2 == f || $2 == "./" f { print $1; exit }'
}

ARM64_DARWIN="poly-${VERSION}-aarch64-apple-darwin.tar.gz"
X86_64_DARWIN="poly-${VERSION}-x86_64-apple-darwin.tar.gz"
ARM64_LINUX="poly-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
X86_64_LINUX="poly-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"

SHA_ARM64_DARWIN="$(sha_for "$ARM64_DARWIN")"
SHA_X86_64_DARWIN="$(sha_for "$X86_64_DARWIN")"
SHA_ARM64_LINUX="$(sha_for "$ARM64_LINUX")"
SHA_X86_64_LINUX="$(sha_for "$X86_64_LINUX")"

for name in SHA_ARM64_DARWIN SHA_X86_64_DARWIN SHA_ARM64_LINUX SHA_X86_64_LINUX; do
  if [ -z "${!name}" ]; then
    echo "Missing checksum for $name in ${BASE_URL}/sha256sums.txt" >&2
    exit 1
  fi
done

cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Poly < Formula
  desc "Universal zero-dependency linter and formatter"
  homepage "https://github.com/Goldziher/poly"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE_URL}/${ARM64_DARWIN}"
      sha256 "${SHA_ARM64_DARWIN}"
    end
    on_intel do
      url "${BASE_URL}/${X86_64_DARWIN}"
      sha256 "${SHA_X86_64_DARWIN}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/${ARM64_LINUX}"
      sha256 "${SHA_ARM64_LINUX}"
    end
    on_intel do
      url "${BASE_URL}/${X86_64_LINUX}"
      sha256 "${SHA_X86_64_LINUX}"
    end
  end

  def install
    bin.install "poly"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/poly --version")
  end
end
EOF
