#!/usr/bin/env bash
set -euo pipefail

# update-homebrew-formula.sh <version> <source-sha256>
#
# Emits a Homebrew *source* formula (to stdout) that builds the `poly` binary
# from the tagged GitHub source tarball with Cargo. This is the bottle-able
# shape: the release workflow pushes this formula to Goldziher/homebrew-tap and
# then dispatches the tap's `bottle.yml`, which runs `brew install --build-bottle`
# + `brew bottle` on each platform and merges the resulting `bottle do` block
# back into this formula. Users on a bottled platform get the prebuilt bottle;
# everyone else builds from source.
#
# <source-sha256> is the sha256 of
#   https://github.com/Goldziher/polylint/archive/refs/tags/v<version>.tar.gz

if [ $# -ne 2 ]; then
  echo "Usage: $0 <version> <source-sha256>" >&2
  exit 1
fi

VERSION="$1"
SHA256="$2"
URL="https://github.com/Goldziher/polylint/archive/refs/tags/v${VERSION}.tar.gz"

cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Polylint < Formula
  desc "Universal zero-dependency linter and formatter"
  homepage "https://github.com/Goldziher/polylint"
  url "${URL}"
  sha256 "${SHA256}"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/poly-cli")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/poly --version")
  end
end
EOF
