//! End-to-end coverage of poly's generated-file handling, through the built
//! binary: arg parsing → config → runner → report → exit code.
//!
//! Three behaviours that were once three different answers to the same
//! question, and are now one:
//!
//! - a `DO NOT EDIT` banner does not hold any phase back — `lint`, `fmt` and
//!   `lint --fix` all act on the file;
//! - a `<project>:hash:<digest>` stamp still withholds the *rewrite*, in `fmt`
//!   and in `lint --fix` alike, because reformatting a stamped body puts the
//!   generator's verify step into a regen loop;
//! - `[discovery] generated = false` (or `--skip-generated`) takes the file out
//!   of both phases, and says so — the skip is reported, so `--deny-skips` can
//!   fail a gate that quietly stopped covering the tree.
#![cfg(unix)]

use std::path::Path;
use std::process::{Command, Output};

const POLY: &str = env!("CARGO_BIN_EXE_poly");

/// A banner-only generated file with an unused import (ruff autofixes it) and
/// loose spacing (the formatter rewrites it).
const BANNER: &str = "\
# This file is auto-generated by alef — DO NOT EDIT.
import asyncio


def extract( inputs ):
    return  inputs
";

/// The same file with a content-hash stamp beneath the banner: the shape that
/// still withholds a rewrite.
const STAMPED: &str = "\
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef
import asyncio


def extract( inputs ):
    return  inputs
";

fn poly(root: &Path, args: &[&str]) -> Output {
    Command::new(POLY)
        .args(args)
        .current_dir(root)
        .output()
        .expect("run poly")
}

fn combined(output: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

fn repo(config: Option<&str>) -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(dir.path().join("banner.py"), BANNER).expect("write banner.py");
    std::fs::write(dir.path().join("stamped.py"), STAMPED).expect("write stamped.py");
    if let Some(body) = config {
        std::fs::write(dir.path().join("poly.toml"), body).expect("write poly.toml");
    }
    dir
}

fn read(dir: &Path, name: &str) -> String {
    std::fs::read_to_string(dir.join(name)).expect("read fixture")
}

/// The default, and the alignment this test exists for: a banner announces
/// provenance, not a checksum, so every phase treats the file as ordinary
/// source. `lint --fix` used to be the odd one out here — it withheld on any
/// generated marker while `fmt` happily reformatted the same file.
#[test]
fn a_banner_only_generated_file_is_linted_formatted_and_fixed() {
    let dir = repo(None);

    let output = poly(dir.path(), &["lint", "--no-cache", "--no-workspace", "banner.py"]);
    let text = combined(&output);
    assert!(text.contains("F401") || text.contains("asyncio"), "got:\n{text}");
    assert!(
        !text.contains("not fixed"),
        "nothing was withheld, so nothing must say so, got:\n{text}"
    );

    let output = poly(
        dir.path(),
        &["lint", "--fix", "--no-cache", "--no-workspace", "banner.py"],
    );
    assert!(
        !read(dir.path(), "banner.py").contains("import asyncio"),
        "--fix must remove the unused import, got:\n{}",
        combined(&output)
    );

    let output = poly(dir.path(), &["fmt", "--fix", "--no-cache", "banner.py"]);
    assert!(
        !read(dir.path(), "banner.py").contains("def extract( inputs )"),
        "fmt must reformat a banner-only file, got:\n{}",
        combined(&output)
    );
}

/// The guard that survives: a stamped body is reported on but never rewritten,
/// by either phase. Reformatting invalidates the hash, so the generator's verify
/// step reports drift on a file no human touched and the remedy is a regen that
/// discards the change.
#[test]
fn a_hash_stamped_file_is_reported_but_never_rewritten() {
    let dir = repo(None);

    let output = poly(
        dir.path(),
        &["lint", "--fix", "--no-cache", "--no-workspace", "stamped.py"],
    );
    let text = combined(&output);
    assert_eq!(
        read(dir.path(), "stamped.py"),
        STAMPED,
        "lint --fix rewrote a stamped file"
    );
    assert!(
        text.contains("not fixed") && text.contains("--fix-generated"),
        "the withheld fix must be visible and name the way in, got:\n{text}"
    );

    let output = poly(dir.path(), &["fmt", "--fix", "--no-cache", "stamped.py"]);
    let text = combined(&output);
    assert_eq!(read(dir.path(), "stamped.py"), STAMPED, "fmt rewrote a stamped file");
    assert!(text.contains("hash-stamped generated file"), "got:\n{text}");

    // And the escape hatch still opens both, so this is a withheld write rather
    // than a file poly cannot process.
    poly(
        dir.path(),
        &["fmt", "--fix", "--fix-generated", "--no-cache", "stamped.py"],
    );
    assert_ne!(
        read(dir.path(), "stamped.py"),
        STAMPED,
        "--fix-generated must still reach a stamped file"
    );
}

/// `[discovery] generated = false` reaches both phases from one key, and the
/// files it removes are reported as skipped rather than dropped.
#[test]
fn the_config_opt_out_skips_generated_files_in_both_phases() {
    let dir = repo(Some("[discovery]\ngenerated = false\n"));

    for args in [
        vec!["lint", "--no-cache", "--no-workspace", "--verbose", "."],
        vec!["fmt", "--check", "--no-cache", "--verbose", "."],
    ] {
        let output = poly(dir.path(), &args);
        let text = combined(&output);
        assert!(
            text.contains("machine-generated file ([discovery] generated = false)"),
            "{args:?} must report the skip and name the key, got:\n{text}"
        );
        assert!(text.contains("banner.py"), "{args:?} got:\n{text}");
        assert!(text.contains("stamped.py"), "{args:?} got:\n{text}");
    }

    // Reported, therefore countable: a gate can make it fatal.
    let output = poly(
        dir.path(),
        &["lint", "--no-cache", "--no-workspace", "--deny-skips", "."],
    );
    assert_eq!(
        output.status.code(),
        Some(2),
        "--deny-skips must fail on the opt-out's skips, got:\n{}",
        combined(&output)
    );

    // And nothing was written by the run that skipped them.
    assert_eq!(read(dir.path(), "banner.py"), BANNER);
    poly(dir.path(), &["fmt", "--fix", "--no-cache", "."]);
    assert_eq!(read(dir.path(), "banner.py"), BANNER, "fmt --fix ignored the opt-out");
}

/// The flags override the config in both directions, and `--fix-generated` —
/// which is about rewriting a *stamped* file — is not a way back in.
#[test]
fn the_flags_override_the_config_in_both_directions() {
    let opted_out = repo(Some("[discovery]\ngenerated = false\n"));
    let output = poly(
        opted_out.path(),
        &[
            "lint",
            "--no-cache",
            "--no-workspace",
            "--include-generated",
            "banner.py",
        ],
    );
    let text = combined(&output);
    assert!(
        !text.contains("machine-generated file"),
        "--include-generated must put the file back in the run, got:\n{text}"
    );
    assert!(text.contains("F401") || text.contains("asyncio"), "got:\n{text}");

    // `--fix-generated` is a different question and must not defeat the opt-out.
    let output = poly(
        opted_out.path(),
        &[
            "lint",
            "--fix",
            "--fix-generated",
            "--no-cache",
            "--no-workspace",
            "--verbose",
            "banner.py",
        ],
    );
    let text = combined(&output);
    assert!(text.contains("machine-generated file"), "got:\n{text}");
    assert_eq!(read(opted_out.path(), "banner.py"), BANNER);

    // The other direction: a default config, opted out for one run.
    let default = repo(None);
    let output = poly(
        default.path(),
        &[
            "lint",
            "--no-cache",
            "--no-workspace",
            "--skip-generated",
            "--verbose",
            "banner.py",
        ],
    );
    let text = combined(&output);
    assert!(
        text.contains("machine-generated file ([discovery] generated = false)"),
        "--skip-generated must skip and name the key it overrides, got:\n{text}"
    );
}

/// `--fix-generated` is an accepted flag whose meaning narrowed rather than
/// vanishing: an existing invocation must keep working, on a banner-only file
/// (where it is now a no-op) as well as on a stamped one.
#[test]
fn fix_generated_remains_accepted_on_a_banner_only_file() {
    let dir = repo(None);
    let output = poly(
        dir.path(),
        &[
            "lint",
            "--fix",
            "--fix-generated",
            "--no-cache",
            "--no-workspace",
            "banner.py",
        ],
    );
    assert!(
        output.status.code() != Some(2),
        "the flag must not error, got:\n{}",
        combined(&output)
    );
    assert!(
        !read(dir.path(), "banner.py").contains("import asyncio"),
        "the fix must land, as it does without the flag"
    );
}
