//! Pins poly's hash-stamp window to Alef's, end to end through `poly_core::format`.
//!
//! `HASH_STAMP_HEADER_LINES` in `crates/poly-core/src/filter.rs` is not a poly
//! tuning knob — it mirrors `MARKER_SCAN_LINES` in `alef/src/core/hash.rs` plus
//! the one line `inject_hash_line` offsets the stamp by. Alef accepts its banner
//! at 0-based line 0..=9, writes `alef:hash:<hex>` on the line immediately below
//! it, and `generated_hash_line` reads it back by peeking that same line — so
//! the deepest stamp Alef can both **write and read back** is 0-based index 10.
//!
//! Poly must protect exactly that set. The unit tests in `filter.rs` pin the
//! predicate; this pins the observable behaviour a consumer actually gets: does
//! `poly fmt --fix` leave the file alone, or rewrite it and invalidate the
//! generator's hash? That loop — reformat, hash mismatch, `alef verify` reports
//! drift on a file no human touched, regen discards the formatting — is what the
//! skip exists to break.
//!
//! This coupling has already broken once silently: Alef moved from "bare
//! `alef:hash:` token anywhere in 0..=9" to "banner then peek", which reaches one
//! line deeper, and poly's window stayed one short with nothing failing on either
//! side.
//!
//! **The line numbers below are literals on purpose. Do not refactor them into
//! expressions over `HASH_STAMP_HEADER_LINES` / `ALEF_MARKER_SCAN_LINES`** (they
//! are private to `poly-core` anyway, which is part of the point). A fixture
//! derived from the constant moves with it, so narrowing the constant would leave
//! this test green — which is precisely the failure it exists to catch.

use std::fs;
use std::path::Path;

use poly_core::{Config, RunOptions};

/// The exact banner Alef emits for `//`-comment languages — see the header
/// template in `alef/src/core/hash.rs` (`HEADER_MARKER` is the
/// `"auto-generated by alef"` substring of it).
const ALEF_BANNER: &str = "// This file is auto-generated by alef — DO NOT EDIT.";
/// A real 64-hex blake3 stamp, in the shape `inject_hash_line` writes for `//`
/// languages. Deliberately full length: an 8-hex digest would still satisfy
/// `MINIMUM_HASH_DIGEST_LENGTH` and so would not exercise what Alef emits.
const ALEF_STAMP: &str = "// alef:hash:a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef";

/// An Alef-shaped generated JavaScript file whose stamp sits at 0-based
/// `stamp_line`, reached by padding a licence preamble above the banner.
///
/// The body is deliberately mis-formatted so that "poly did not skip it" is
/// observable as a real rewrite rather than as a no-op that would pass either
/// way. JavaScript keeps this hermetic: the oxc backend is compiled in, so
/// nothing here depends on a tool being installed on the host.
fn alef_generated_js(stamp_line: usize) -> String {
    let banner_line = stamp_line - 1;
    let mut source = "// Copyright 2026 xberg-io\n".repeat(banner_line);
    source.push_str(ALEF_BANNER);
    source.push('\n');
    source.push_str(ALEF_STAMP);
    source.push('\n');
    source.push_str("// To regenerate: alef generate\n\nconst   bridge = {a:1,   b:2}\n");
    source
}

fn write_fixture(dir: &Path, name: &str, content: &str) -> std::path::PathBuf {
    let path = dir.join(name);
    fs::write(&path, content).unwrap();
    path
}

/// `no_cache` keeps this off the developer's real result cache entirely
/// (`ResultCache::open_default(!no_cache)`), so the test needs no
/// `POLY_CACHE_HOME` override and no process-global environment mutation.
fn format_options() -> RunOptions {
    RunOptions {
        no_cache: true,
        jobs: Some(1),
        explicit_config: true,
        fix_generated: false,
        ..RunOptions::default()
    }
}

/// Formats `content` in a private temp dir with `write: true` and returns the
/// skip reason (if any) plus the file's bytes afterwards.
fn format_in_place(content: &str) -> (Option<String>, bool, String) {
    let dir = tempfile::tempdir().unwrap();
    let path = write_fixture(dir.path(), "bridge.js", content);
    let results = poly_core::format(
        &[dir.path().to_path_buf()],
        &Config::default(),
        &format_options(),
        true,
        false,
    )
    .unwrap();
    assert_eq!(results.len(), 1, "expected exactly one discovered file");
    assert_eq!(results[0].error, None, "the fixture must format cleanly, not error");
    (
        results[0].skipped.clone(),
        results[0].changed,
        fs::read_to_string(&path).unwrap(),
    )
}

/// The stamp Alef can write *and* read back at its deepest: banner at 0-based
/// line 9, stamp at 0-based line 10. Poly must skip it.
#[test]
fn should_skip_a_stamp_at_the_deepest_line_alef_can_reach() {
    let source = alef_generated_js(10);
    assert_eq!(
        source.lines().position(|line| line.contains("alef:hash:")),
        Some(10),
        "fixture must place the stamp at 0-based line 10, or it proves nothing"
    );
    assert_eq!(
        source.lines().position(|line| line.contains("auto-generated by alef")),
        Some(9),
        "the banner must sit at 0-based line 9 — Alef's deepest accepted marker line"
    );

    let (skipped, changed, on_disk) = format_in_place(&source);
    assert_eq!(
        skipped.as_deref(),
        Some("hash-stamped generated file (pass --fix-generated to format)"),
        "a stamp at the producer's deepest reachable line must be honored"
    );
    assert!(!changed, "a skipped file must not be reported as changed");
    assert_eq!(
        on_disk, source,
        "a skipped file must be left byte-for-byte unchanged, or the generator's hash is invalidated"
    );
}

/// One line past the producer's reach: banner at 0-based line 10, stamp at 11.
/// Alef itself cannot read that stamp back, so poly must not skip on it — a
/// wider window silently drops hand-written files out of the format gate, which
/// `filter.rs` weighs as strictly worse than reformatting a generated one.
///
/// This is the non-vacuity half: it proves the file above was skipped *because
/// of the stamp*, not because poly declines this fixture shape generally.
#[test]
fn should_not_skip_a_stamp_past_the_producer_window() {
    let source = alef_generated_js(11);
    assert_eq!(
        source.lines().position(|line| line.contains("alef:hash:")),
        Some(11),
        "fixture must place the stamp one past the producer's reach"
    );

    let (skipped, changed, on_disk) = format_in_place(&source);
    assert_eq!(
        skipped, None,
        "a stamp deeper than Alef's own reader accepts must not remove the file from the format gate"
    );
    assert!(
        changed,
        "the fixture must actually need reformatting, or the skip assertion above is vacuous"
    );
    assert_ne!(on_disk, source, "a non-skipped file must actually be rewritten on disk");
}
