//! `[discovery] generated` — the one opt-out covering `lint`, `fmt` and `--fix`.
//!
//! The default (act on generated files) is pinned in `pipeline.rs`, next to the
//! hash-stamp guard it must not be confused with. This file pins the opt-out:
//! that it reaches **both** phases from one key, and that a file it removes is
//! *reported* as skipped rather than silently dropped — a silent drop is how a
//! gate stops covering a tree without anything going red.

use std::path::{Path, PathBuf};

use poly_core::{Config, GENERATED_SKIP, RunOptions};

/// A generated Python file with a `DO NOT EDIT` banner and two defects: an
/// unused import (a lint finding ruff can autofix) and, for `fmt`, indentation
/// the formatter rewrites.
///
/// Deliberately banner-only, with no content-hash stamp: a stamped file is
/// withheld from rewriting by a *separate* guard, so using one here would let
/// this test pass for the wrong reason.
const GENERATED_SOURCE: &str = "\
# This file is auto-generated by alef — DO NOT EDIT.
import asyncio


def extract( inputs ):
    return  inputs
";

fn write_generated(dir: &Path) -> PathBuf {
    let path = dir.join("generated.py");
    std::fs::write(&path, GENERATED_SOURCE).expect("write generated");
    path
}

/// `generated = false` in the config used by both calls: one key, both phases.
fn opted_out() -> Config {
    Config {
        generated: false,
        ..Config::default()
    }
}

fn options() -> RunOptions {
    RunOptions {
        no_cache: true,
        ..RunOptions::default()
    }
}

/// The default is to act on generated files, in lint and in fmt alike.
///
/// The control for every assertion below: without it, an opt-out test passes
/// just as well against a poly that never checks a generated file at all.
#[test]
fn generated_files_are_linted_and_formatted_by_default() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = write_generated(dir.path());
    let paths = std::slice::from_ref(&path);

    let lint = poly_core::lint_run(paths, &Config::default(), &options(), false, false).expect("lint");
    assert!(
        !lint.results.is_empty(),
        "a generated file is linted by default — that is how a generator bug is noticed"
    );
    assert_eq!(lint.checked, 1, "and it counts as checked");
    assert!(lint.skipped.is_empty(), "nothing was skipped: {:?}", lint.skipped);

    let format = poly_core::format(paths, &Config::default(), &options(), false, false).expect("format");
    assert_eq!(format.len(), 1);
    assert!(format[0].changed, "a generated file is formatted by default");
    assert_eq!(format[0].skipped, None);
}

/// The opt-out removes the file from the lint run, and says so.
///
/// The skip is the load-bearing half. It keeps the file out of `checked`, puts
/// it in the `skipped` payload every reporter renders, and lets
/// `--deny-skips` / `--max-skips` fail a run that quietly stopped covering a
/// tree. The reason names the key, so a reader who did not write the line can
/// still find it.
#[test]
fn opting_out_skips_generated_files_in_lint_and_names_the_key() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = write_generated(dir.path());

    let run = poly_core::lint_run(std::slice::from_ref(&path), &opted_out(), &options(), false, false).expect("lint");

    assert!(run.results.is_empty(), "no findings from a file that was not linted");
    assert_eq!(run.checked, 0, "an uninspected file must not be counted as checked");
    assert_eq!(run.skipped.len(), 1, "the file must be reported, not dropped");
    assert_eq!(run.skipped[0].path, path);
    assert_eq!(run.skipped[0].reason, GENERATED_SKIP);
    assert_eq!(
        run.skipped[0].reason, "machine-generated file ([discovery] generated = false)",
        "the reason must name the key that produced it"
    );
}

/// The same key reaches `fmt`, which is the point of moving it out of `[lint]`:
/// a reader who opted out of checking generated files did not mean "…except
/// when I run the formatter".
#[test]
fn opting_out_skips_generated_files_in_fmt_too() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = write_generated(dir.path());

    let run = poly_core::format_run(std::slice::from_ref(&path), &opted_out(), &options(), true, false).expect("fmt");

    assert_eq!(run.results.len(), 1);
    assert!(
        !run.results[0].changed,
        "an opted-out file must not be reported as drift"
    );
    assert_eq!(run.results[0].skipped.as_deref(), Some(GENERATED_SKIP));
    assert_eq!(run.skipped.len(), 1, "and it reaches the run-level skip list");
    assert_eq!(run.skipped[0].reason, GENERATED_SKIP);
    assert_eq!(
        std::fs::read_to_string(&path).expect("read"),
        GENERATED_SOURCE,
        "write mode must leave the file byte-identical"
    );
}

/// `--fix` cannot reach a file the opt-out kept out of the run: there is nothing
/// to fix in a file nothing linted, so the file stays byte-identical and the run
/// still reports the skip rather than a clean pass.
#[test]
fn opting_out_withholds_fixes_because_nothing_was_linted() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = write_generated(dir.path());

    let run = poly_core::lint_run(std::slice::from_ref(&path), &opted_out(), &options(), true, false).expect("lint");

    assert_eq!(
        std::fs::read_to_string(&path).expect("read"),
        GENERATED_SOURCE,
        "--fix must not rewrite a file the run never checked"
    );
    assert_eq!(run.skipped.len(), 1);
    assert_eq!(run.skipped[0].reason, GENERATED_SKIP);
}

/// `--fix-generated` is about *rewriting* a hash-stamped file, not about what
/// the run examines. It must not read as a way back into a run the opt-out
/// closed — otherwise a repository that opted out would silently start linting
/// generated files the moment someone passed an unrelated flag.
#[test]
fn fix_generated_does_not_defeat_the_opt_out() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = write_generated(dir.path());
    let options = RunOptions {
        no_cache: true,
        fix_generated: true,
        ..RunOptions::default()
    };

    let run = poly_core::lint_run(std::slice::from_ref(&path), &opted_out(), &options, true, false).expect("lint");

    assert_eq!(run.checked, 0);
    assert_eq!(run.skipped.len(), 1);
    assert_eq!(run.skipped[0].reason, GENERATED_SKIP);
    assert_eq!(std::fs::read_to_string(&path).expect("read"), GENERATED_SOURCE);
}

/// The per-run override (`--skip-generated` / `--include-generated`) beats the
/// config in both directions. An override a config could veto would not be one.
#[test]
fn the_run_level_override_beats_the_config_in_both_directions() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = write_generated(dir.path());
    let paths = std::slice::from_ref(&path);
    let with = |generated: Option<bool>| RunOptions {
        no_cache: true,
        generated,
        ..RunOptions::default()
    };

    // `--skip-generated` over a default config.
    let run = poly_core::lint_run(paths, &Config::default(), &with(Some(false)), false, false).expect("lint");
    assert_eq!(run.checked, 0);
    assert_eq!(run.skipped.len(), 1);
    assert_eq!(run.skipped[0].reason, GENERATED_SKIP);

    // `--include-generated` over a config that opted out.
    let run = poly_core::lint_run(paths, &opted_out(), &with(Some(true)), false, false).expect("lint");
    assert_eq!(run.checked, 1, "the flag must put the file back in the run");
    assert!(run.skipped.is_empty());

    // And the same file, same configs, with no flag: the config decides.
    let run = poly_core::lint_run(paths, &opted_out(), &with(None), false, false).expect("lint");
    assert_eq!(run.checked, 0);
}

/// A hand-written file is untouched by the opt-out, so none of the above can be
/// mistaken for "poly stopped checking things".
#[test]
fn the_opt_out_does_not_reach_hand_written_files() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("handwritten.py");
    std::fs::write(
        &path,
        "import asyncio\n\n\ndef extract( inputs ):\n    return  inputs\n",
    )
    .expect("write");

    let run = poly_core::lint_run(std::slice::from_ref(&path), &opted_out(), &options(), false, false).expect("lint");

    assert_eq!(run.checked, 1);
    assert!(run.skipped.is_empty(), "{:?}", run.skipped);
    assert!(!run.results.is_empty());
}
