//! Content-based skip detection: file-level "do not format" directives,
//! machine-generated banners, and the content-hash stamps a generator writes
//! over a file body and later verifies.

use crate::language::Language;

/// Whether `content` carries a file-level "do not format this file" directive
/// for its `language`, in which case `poly fmt` leaves it untouched.
///
/// As the umbrella formatter, poly honors the ecosystem's established
/// whole-file skip markers so it does not fight a tool a project already opted
/// into (and does not disturb machine-generated bridge/glue files that carry
/// the marker). Currently:
///
/// - **Swift** — `// swift-format-ignore-file` (the directive `swift-format`
///   itself recognizes to skip a file entirely). Matched leniently anywhere in
///   the file; it is a distinctive marker that does not occur incidentally.
pub(crate) fn is_format_ignored(content: &str, language: &Language) -> bool {
    match language {
        Language::Swift => content.contains("swift-format-ignore-file"),
        _ => false,
    }
}

/// Markers that identify a machine-generated file, matched case-insensitively
/// against its opening lines.
///
/// Deliberately narrow: each is a phrase a generator writes to tell humans not
/// to edit the file, not merely a mention of generation.
const GENERATED_MARKERS: &[&str] = &[
    "do not edit",
    "@generated",
    "auto-generated",
    "autogenerated",
    "auto generated",
    "code generated",
];

/// How many opening lines are searched for a generated-file marker. Generators
/// put the banner at the top; scanning further would start matching prose.
const GENERATED_HEADER_LINES: usize = 5;

/// Alef's own marker-scan bound, mirrored here.
///
/// Upstream: `MARKER_SCAN_LINES` in `alef/src/core/hash.rs`. Both
/// `inject_hash_line` (the writer) and `generated_hash_line` (the reader) bound
/// their search for the generated-file banner by it, so Alef accepts its banner
/// at 0-based line 0..=9 and nowhere deeper.
///
/// This is a **mirrored upstream value, not a poly tuning knob.** The only
/// correct reason to change it is that Alef changed `MARKER_SCAN_LINES`; the
/// only correct response to Alef changing `MARKER_SCAN_LINES` is to change it
/// here. Nothing in either repo fails when the two drift — poly simply stops
/// protecting files the producer can still stamp (see the note on
/// [`HASH_STAMP_HEADER_LINES`], which this already caused once). The behaviour
/// is pinned by `should_honor_the_producer_stamp_window_exactly` below and by
/// `crates/poly-core/tests/alef_stamp_window.rs`, both written against literal
/// line numbers so that narrowing either constant cannot leave them green.
const ALEF_MARKER_SCAN_LINES: usize = 10;

/// How many lines **of [`generated_header_region`]** are searched for a
/// structured content-hash stamp. Like [`GENERATED_HEADER_LINES`] this is
/// measured from the start of that region, i.e. *after* any YAML frontmatter
/// block — not from byte 0 of the file. A frontmattered document therefore gets
/// this many lines on top of its frontmatter.
///
/// Wider than [`GENERATED_HEADER_LINES`] because this window has to match the
/// producer's, not ours. Alef — the generator that motivated this — accepts its
/// header marker anywhere in the first 10 lines and writes the `alef:hash:<hex>`
/// line directly beneath it, so a stamp legitimately lands well below line 5
/// whenever a licence preamble, SPDX block, or build-tag stanza precedes the
/// banner. Scanning only 5 left exactly those files unprotected: stamped by the
/// generator, invisible to poly, reformatted by `fmt --fix` — and the reflow then
/// reported as drift by the generator's own verify step, which is the loop the
/// skip exists to break. A consumer's vendored cgo and visitor bindings were the
/// casualties.
///
/// **This value is derived from Alef, not chosen.** [`ALEF_MARKER_SCAN_LINES`]
/// bounds where the banner may sit (index 0..=9). The `+ 1` is the injector's
/// offset: `inject_hash_line` writes the stamp on the line *below* the banner
/// and `generated_hash_line` reads it back by peeking that same line, so the
/// deepest stamp Alef can both write and read is index 10 — eleven lines of
/// window. Poly's window is the producer's window plus that one line, and
/// neither term is free to move on its own.
///
/// (An earlier revision of Alef read a bare `alef:hash:` token anywhere in
/// index 0..=9, so poly matched it at 10. Alef then moved to marker-then-peek,
/// which reaches one line deeper, and poly was silently one short until this was
/// noticed by hand — no test failed on either side. That is the failure this
/// derivation exists to make loud.)
///
/// Widening is safe *only* for the structured shape. `<project>:hash:<8+ hex>`
/// (see [`has_structured_hash_stamp`]) cannot occur in prose. The loose banners
/// and the bare-word [`CONTENT_HASH_MARKERS`] keep the narrow window: those are
/// English words that appear further down real files, and a false skip there
/// drops a hand-written file out of the format gate silently — the failure this
/// module weighs as strictly worse than formatting a generated file.
const HASH_STAMP_HEADER_LINES: usize = ALEF_MARKER_SCAN_LINES + 1;

fn generated_header_region(content: &str) -> Option<&str> {
    let mut offset = 0;
    for (index, line) in content.split_inclusive('\n').enumerate() {
        let line_content = line.trim_end_matches(['\r', '\n']);
        if index == 0 && line_content != "---" {
            return Some(content);
        }
        offset += line.len();
        if index > 0 && line_content == "---" {
            return Some(&content[offset..]);
        }
    }
    (!content.starts_with("---")).then_some(content)
}

/// Whether `content` announces itself as machine-generated.
///
/// `poly lint` still *reports* on these files — that is how a generator bug gets
/// noticed — but `--fix` leaves them alone, because rewriting generated output
/// is churn that the next generation run reverts, and worse, it can silence the
/// diagnostic that was the only evidence of the bug.
///
/// The case that motivated this: ruff's `F841` correctly fired on an unused
/// binding in a generated test, and that binding was the sole signal that 39
/// generated tests across 8 files called an API and asserted nothing. Running
/// `--fix` rewrote it to `_` and turned a loud, correct diagnostic about a real
/// upstream defect into a clean lint pass.
pub(crate) fn is_generated_source(content: &str) -> bool {
    generated_header_region(content).is_some_and(|header| {
        header.lines().take(GENERATED_HEADER_LINES).any(|line| {
            let lower = line.to_ascii_lowercase();
            GENERATED_MARKERS.iter().any(|marker| lower.contains(marker))
        }) || has_content_hash_stamp(header)
    })
}

/// Markers that mean the header carries a **content hash** of the file body.
const CONTENT_HASH_MARKERS: &[&str] = &["sourcehash", "@checksum"];
const STRUCTURED_HASH_MARKER: &str = ":hash:";

/// Hex lengths a real content hash can have: md5, sha1, sha224, sha256/blake3,
/// sha384, sha512.
///
/// Checking membership rather than a minimum is what separates a stamp from a
/// hex-looking token. A consumer measured the previous `>= 8` rule and found it
/// accepted 8, 63 and 65 hex characters — no digest is 63 or 65 characters, and
/// 8 is short enough to occur by accident — so each of those silently dropped a
/// hand-written file out of the format gate.
///
/// Deliberately *not* pinned to 64. Poly's marker is generator-agnostic
/// (`<project>:hash:<digest>`); 64 is only what one generator emits because it
/// uses blake3. Pinning to it would drop every sha1- or md5-stamped generator
/// out of the gate — the same defect aimed at a different producer.
const HASH_DIGEST_LENGTHS: &[usize] = &[32, 40, 56, 64, 96, 128];

/// What may legally follow the digest: nothing, whitespace, or a comment
/// terminator. A stamp is a whole comment line, so a token wrapped in something
/// else — markdown backticks being the case that was measured — is prose that
/// happens to mention a hash, not a stamp.
const DIGEST_TERMINATORS: &[&str] = &["-->", "*/", "#}", "--%>"];

/// Backticks or tildes needed to open a code fence, and the indent at which a
/// line becomes an indented code block instead.
const MIN_FENCE_RUN: usize = 3;

/// Strips the container prefixes a fence can be nested behind — blockquote
/// markers and list bullets — so the fence itself is still recognized.
///
/// A fence opener inside a list item or a blockquote does not start at column 0;
/// the line leads with `- ` or `> `. Keying fence detection on the raw line start
/// left every nested fence undetected while the unnested shapes read as fixed.
///
/// Only used to decide whether a line *opens or closes a fence*. Over-stripping
/// is therefore harmless unless the remainder is itself a fence, and a mis-read
/// fence is the same class of miss as no fence at all.
fn strip_container_prefix(line: &str) -> &str {
    let mut rest = line.trim_start();
    loop {
        if let Some(stripped) = rest.strip_prefix('>') {
            rest = stripped.trim_start();
            continue;
        }
        // Bullet lists: the marker must be followed by space, or `-` in YAML and
        // `*` in a block comment would be stripped from lines that are neither.
        if let Some(stripped) = ["- ", "* ", "+ "].iter().find_map(|b| rest.strip_prefix(b)) {
            rest = stripped.trim_start();
            continue;
        }
        // Ordered lists: digits followed by `.` or `)` and a space.
        let digits = rest.chars().take_while(char::is_ascii_digit).count();
        if digits > 0
            && let Some(stripped) = rest[digits..]
                .strip_prefix(". ")
                .or_else(|| rest[digits..].strip_prefix(") "))
        {
            rest = stripped.trim_start();
            continue;
        }
        return rest;
    }
}

/// Advances fenced-code-block state and reports whether `line` sits in a fenced
/// code block.
///
/// A hash token inside a code block is documentation *about* a stamp. This is
/// the block-level twin of the inline-backtick case [`DIGEST_TERMINATORS`]
/// rejects: inline, the wrapping is on the same line, so the trailing character
/// gives it away; inside a block the token is genuinely bare and
/// line-terminated, so nothing about the line itself distinguishes it. A
/// document explaining the stamp format was skipped in its entirety — the same
/// false-skip the terminator rule exists to prevent, one level up.
///
/// Covers backtick and tilde fences, any fence length, info strings, and fences
/// nested in lists or blockquotes.
///
/// **Indented code blocks are deliberately not covered.** Treating a 4-space
/// indent as code is a CommonMark rule, and it is the one rule here that could
/// *widen* the skip rather than narrow it — every other shape removes a false
/// skip. A consumer survey found 1236 of 1265 live stamps in languages where
/// indentation is structural and carries no code-block meaning (Java, Kotlin,
/// Python, Go, Zig), and 48 already sitting at one leading space — three from
/// the threshold. Suppressing there would trade this false skip for a
/// differently-shaped one, so indented blocks stay known-bad pending a ruling.
fn is_in_code_block(fence: &mut Option<(char, usize)>, line: &str) -> bool {
    let content = strip_container_prefix(line);

    if let Some(delimiter) = content.chars().next().filter(|c| matches!(c, '`' | '~')) {
        let run = content.chars().take_while(|character| *character == delimiter).count();
        if run >= MIN_FENCE_RUN {
            match *fence {
                // A fence closes only on its own delimiter, at least as long as
                // the opener, and carrying no info string; anything else is
                // content inside the block.
                Some((open, open_run)) if delimiter == open && run >= open_run && content[run..].trim().is_empty() => {
                    *fence = None;
                }
                Some(_) => {}
                None => *fence = Some((delimiter, run)),
            }
            return true;
        }
    }

    fence.is_some()
}

fn has_structured_hash_stamp(line: &str) -> bool {
    let header = line.trim_start_matches(|character: char| !character.is_ascii_alphanumeric());
    let Some((project, digest)) = header.split_once(STRUCTURED_HASH_MARKER) else {
        return false;
    };
    if project.is_empty()
        || !project
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, '_' | '-'))
    {
        return false;
    }

    let digest = digest.trim_start();
    let hex_length = digest.chars().take_while(char::is_ascii_hexdigit).count();
    if !HASH_DIGEST_LENGTHS.contains(&hex_length) {
        return false;
    }

    // Whatever follows the digest must close the line or close the comment.
    // Anything else means the token was embedded in something — prose quoting a
    // hash rather than a header stamping one.
    let trailing = digest[hex_length..].trim();
    trailing.is_empty() || DIGEST_TERMINATORS.contains(&trailing)
}

/// Whether `header` carries a content-hash stamp over the body.
///
/// The two signal classes get different windows on purpose — see
/// [`HASH_STAMP_HEADER_LINES`]. The structured `<project>:hash:<hex>` shape is
/// searched to the producer's depth; the bare-word markers stay inside the
/// narrow banner window, because a lone `sourcehash` is an identifier that
/// occurs in ordinary code and a false positive here silently removes a
/// hand-written file from the format gate.
fn has_content_hash_stamp(header: &str) -> bool {
    let mut fence = None;
    header
        .lines()
        .take(HASH_STAMP_HEADER_LINES)
        .enumerate()
        .any(|(index, line)| {
            // Tracked over every scanned line, not just candidates, so the fence
            // state is correct by the time a candidate appears.
            if is_in_code_block(&mut fence, line) {
                return false;
            }
            let lower = line.to_ascii_lowercase();
            has_structured_hash_stamp(&lower)
                || (index < GENERATED_HEADER_LINES && CONTENT_HASH_MARKERS.iter().any(|marker| lower.contains(marker)))
        })
}

/// Whether the header stamps a content hash over the body.
///
/// This is a strictly narrower question than [`is_generated_source`], and the
/// two drive different decisions:
///
/// - **`lint --fix`** withholds on *any* generated marker. Withholding a fix
///   still reports the diagnostics, so nothing leaves the gate.
/// - **`fmt`** skips only on a content hash, because skipping there removes the
///   file from the format gate entirely.
///
/// The distinction exists because generalising it caused real harm. Reformatting
/// a hash-stamped body invalidates the hash, so a verify step reports drift on a
/// file no human touched and the remedy is a regen that discards the formatting
/// — that is a loop, and skipping breaks it. But a bare "DO NOT EDIT" banner
/// makes no such promise, and a generator that stamps a *hand-written* file with
/// one would silently drop it out of lint and format enforcement — reported by a
/// consumer whose most user-facing code left the gate without anything failing.
/// Formatting a banner-only file is harmless; silently not checking it is not.
pub(crate) fn is_hash_stamped_source(content: &str) -> bool {
    generated_header_region(content).is_some_and(has_content_hash_stamp)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn swift_format_ignore_file_directive_skips_formatting() {
        let ignored = "// swift-format-ignore-file\nimport Foundation\nstruct A{let x:Int}\n";
        assert!(is_format_ignored(ignored, &Language::Swift));
        let normal = "import Foundation\nstruct A{let x:Int}\n";
        assert!(!is_format_ignored(normal, &Language::Swift));
        assert!(!is_format_ignored(ignored, &Language::Python));
    }

    #[test]
    fn should_only_recognize_structured_hash_stamps() {
        for ordinary_source in ["use a::hash::b;\n", "a:hash:b\n"] {
            assert!(!is_generated_source(ordinary_source), "source: {ordinary_source:?}");
            assert!(!is_hash_stamped_source(ordinary_source), "source: {ordinary_source:?}");
        }

        for generated_header in [
            "# alef:hash: a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef\n",
            "// project_2:hash:a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef\n",
        ] {
            assert!(is_generated_source(generated_header), "header: {generated_header:?}");
            assert!(is_hash_stamped_source(generated_header), "header: {generated_header:?}");
        }
    }

    /// The exact header Alef writes: `hash::header(CommentStyle::DoubleSlash)`
    /// followed by `hash::inject_hash_line`, which stamps the line *below* the
    /// banner. Not a generic invented marker.
    fn alef_stamped_source(preamble_lines: usize) -> String {
        let mut source = "// Copyright 2026 xberg-io\n".repeat(preamble_lines);
        source.push_str("// This file is auto-generated by alef — DO NOT EDIT.\n");
        source.push_str("// alef:hash:a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef\n");
        source.push_str("// To regenerate: alef generate\n\npackage bridge\n");
        source
    }

    /// Alef accepts its banner anywhere in the first 10 lines and stamps
    /// directly beneath it, so a licence preamble pushes the stamp past the
    /// banner window. Scanning only 5 lines left those files stamped by the
    /// generator and unprotected in poly — `fmt --fix` reflowed a consumer's
    /// vendored cgo and visitor bindings.
    #[test]
    fn should_skip_stamped_source_when_a_preamble_precedes_the_alef_banner() {
        let source = alef_stamped_source(4);
        assert_eq!(
            source.lines().position(|line| line.contains("alef:hash:")),
            Some(5),
            "fixture must put the stamp past GENERATED_HEADER_LINES, or it proves nothing"
        );
        assert!(is_hash_stamped_source(&source), "fmt would reformat a stamped file");
        assert!(is_generated_source(&source), "lint --fix would rewrite a stamped file");
    }

    /// Both edges of the producer's reach, written as literals on purpose.
    ///
    /// Alef bounds its *marker* scan at index 0..=9 and reads the stamp on the
    /// line immediately after the marker, so the deepest stamp it can both write
    /// and read back is index **10**. Deriving these fixtures from
    /// [`HASH_STAMP_HEADER_LINES`] or [`ALEF_MARKER_SCAN_LINES`] would make them
    /// move with the constant, so narrowing it would leave them green — the
    /// literals are what pin poly's window to the producer's.
    ///
    /// **Do not refactor `9` / `10` / `11` here into expressions over the
    /// constants.** It reads like duplication and is the entire guard: a derived
    /// fixture tests that the code agrees with itself, which it always does.
    /// Same rule in `crates/poly-core/tests/alef_stamp_window.rs`.
    #[test]
    fn should_honor_the_producer_stamp_window_exactly() {
        let deepest_the_producer_can_reach = alef_stamped_source(9);
        assert_eq!(
            deepest_the_producer_can_reach
                .lines()
                .position(|line| line.contains("alef:hash:")),
            Some(10),
            "fixture must place the stamp at the producer's deepest reachable line"
        );
        assert!(
            is_hash_stamped_source(&deepest_the_producer_can_reach),
            "a stamp on the deepest line the producer can reach must be honored"
        );

        let beyond = alef_stamped_source(10);
        assert_eq!(beyond.lines().position(|line| line.contains("alef:hash:")), Some(11));
        assert!(
            !is_hash_stamped_source(&beyond),
            "a stamp deeper than the producer's own reader accepts must not skip"
        );
    }

    /// The wider window admits the structured shape only. Widening the loose
    /// banners would drop hand-written files out of the format gate silently,
    /// which this module treats as strictly worse than formatting a generated
    /// one.
    #[test]
    fn should_not_widen_the_window_for_prose_banners_or_bare_word_markers() {
        let banner_below_window = format!("{}// DO NOT EDIT.\nfn main() {{}}\n", "// filler\n".repeat(6));
        assert!(!is_generated_source(&banner_below_window));
        assert!(!is_hash_stamped_source(&banner_below_window));

        let bare_word_below_window = format!("{}let sourcehash = compute();\n", "// filler\n".repeat(6));
        assert!(
            !is_hash_stamped_source(&bare_word_below_window),
            "a `sourcehash` identifier below the banner window must not remove the file from the gate"
        );

        let bare_word_inside_window = "// sourcehash: abc\nfn main() {}\n";
        assert!(
            is_hash_stamped_source(bare_word_inside_window),
            "the narrow-window behavior of the bare-word markers is unchanged"
        );
    }

    /// A hex-looking token is not a digest. The previous rule accepted any run
    /// of 8 or more hex characters, which a consumer measured as accepting 8, 63
    /// and 65 — no digest is 63 or 65 characters long, and 8 is short enough to
    /// occur by accident. Each accepted length silently dropped a hand-written
    /// file out of the format gate.
    #[test]
    fn should_reject_digests_that_are_not_a_real_hash_length() {
        for length in [1usize, 7, 8, 16, 31, 63, 65, 127] {
            let source = format!("# alef:hash:{}\nbody\n", "a".repeat(length));
            assert!(
                !is_hash_stamped_source(&source),
                "{length} hex characters is not a digest length and must not skip"
            );
        }

        // Every real digest length a generator can emit still counts. Pinning
        // this to 64 would drop sha1- or md5-stamped generators out of the gate.
        for length in HASH_DIGEST_LENGTHS {
            let source = format!("# alef:hash:{}\nbody\n", "a".repeat(*length));
            assert!(
                is_hash_stamped_source(&source),
                "{length} hex characters is a real digest length and must skip"
            );
        }
    }

    /// Stamp matching is case-insensitive, in the marker keyword, the project
    /// name and the digest alike — [`has_content_hash_stamp`] folds the line to
    /// lowercase before any of the shape checks run.
    ///
    /// This is a deliberate acceptance, recorded here because a consumer survey
    /// found it undecided: across a 1265-stamp corpus every digest was lowercase,
    /// so no generator observed today depends on it. Rejecting uppercase would
    /// nonetheless be a gratuitous restriction on producers — hex is
    /// case-insensitive by definition, and the marker is generator-agnostic, so
    /// a generator emitting `SHA256`-style uppercase is stamping correctly. The
    /// cost of accepting it is bounded by the same length and terminator rules
    /// that bound the lowercase form.
    ///
    /// The rejection half of this test is the part that matters: it proves the
    /// case folding happens *before* the shape checks rather than opening a
    /// second, looser path around them.
    #[test]
    fn digest_matching_is_case_insensitive_without_loosening_the_shape_rules() {
        let upper = "ABCDEF0123456789".repeat(4);
        assert_eq!(upper.len(), 64, "fixture must be a canonical digest length");

        for accepted in [
            format!("# alef:hash:{upper}\nbody\n"),
            format!("# ALEF:HASH:{upper}\nbody\n"),
            format!("<!-- Alef:Hash:{upper} -->\nbody\n"),
        ] {
            assert!(
                is_hash_stamped_source(&accepted),
                "uppercase is a valid spelling of a canonical digest: {accepted:?}"
            );
        }

        // Case folding must not become an escape hatch: an uppercase token still
        // has to be a real digest length, and still has to terminate the line.
        for rejected in [
            format!("# alef:hash:{}\nbody\n", &upper[..63]),
            format!("# ALEF:HASH:{}\nbody\n", &upper[..63]),
            format!("`ALEF:HASH:{upper}`\nbody\n"),
            format!("# ALEF:HASH:{upper} and then some prose\nbody\n"),
        ] {
            assert!(
                !is_hash_stamped_source(&rejected),
                "uppercase must not bypass the length and terminator rules: {rejected:?}"
            );
        }
    }

    /// A hash token inside a fenced code block is documentation *about* a stamp.
    ///
    /// This is the block-level twin of the inline-backtick case: there the
    /// wrapping sits on the same line, so the trailing character rejects it, but
    /// inside a fence the token is genuinely bare and line-terminated. A document
    /// explaining the stamp format was therefore skipped in its entirety — the
    /// exact false-skip the terminator rule exists to prevent.
    #[test]
    fn a_hash_token_inside_a_fenced_code_block_is_documentation_not_a_stamp() {
        let digest = "a1b2c3d4".repeat(8);

        // Every block-code shape a consumer measured, run through BOTH arms: a
        // raw file, and a file whose window is counted after a frontmatter
        // block. The arms reach the scan through different call paths, and a fix
        // landing in one of them satisfies half a table while reading as
        // complete — which is how the first count of this defect came in low.
        let shapes: [(&str, String); 10] = [
            ("fence_backtick", format!("```\nalef:hash:{digest}\n```")),
            ("fence_tilde", format!("~~~\nalef:hash:{digest}\n~~~")),
            ("fence_info_string", format!("```text\nalef:hash:{digest}\n```")),
            // A tilde fence carrying an info string is its own shape: it fails
            // whenever info-string handling is written on the backtick path
            // only, which is the natural way to write it.
            ("fence_tilde_tagged", format!("~~~text\nalef:hash:{digest}\n~~~")),
            ("fence_long", format!("`````\nalef:hash:{digest}\n`````")),
            ("fence_indented", format!("   ```\nalef:hash:{digest}\n   ```")),
            ("fence_in_list", format!("- item\n\n  ```\n  alef:hash:{digest}\n  ```")),
            ("blockquote_fence", format!("> ```\n> alef:hash:{digest}\n> ```")),
            (
                "nested_blockquote_list",
                format!("> - item\n>\n>   ```\n>   alef:hash:{digest}\n>   ```"),
            ),
            (
                "ordered_list_fence",
                format!("1. item\n\n   ```\n   alef:hash:{digest}\n   ```"),
            ),
        ];

        for (name, block) in &shapes {
            let raw = format!("# Doc\n\nGenerators write:\n\n{block}\n\nbody\n");
            assert!(
                !is_hash_stamped_source(&raw),
                "{name}: a token inside a code block documents a stamp, it is not one: {raw:?}"
            );

            let framed = format!("---\ntitle: Doc\n---\n\n{block}\n\nbody\n");
            assert!(
                !is_hash_stamped_source(&framed),
                "{name}: the post-frontmatter arm must suppress the same shape: {framed:?}"
            );
        }

        // A fence opening on the very first line, with no preamble to displace it.
        let first_line = format!("```\nalef:hash:{digest}\n```\n\nbody\n");
        assert!(!is_hash_stamped_source(&first_line), "a fence may open on line 1");

        // An inline code span is *not* a block context; it is already rejected by
        // the terminator rule, and must stay rejected for that reason.
        let inline = format!("# Doc\n\nWrites `alef:hash:{digest}` inline.\n\nbody\n");
        assert!(
            !is_hash_stamped_source(&inline),
            "an inline span is prose quoting a hash"
        );

        // Protect controls. Suppression is scoped to the block, so a real stamp
        // outside one still counts — including the indented block-comment
        // continuation shape that 48 live stamps actually use.
        let protect: [(&str, String); 4] = [
            (
                "real_html_stamp",
                format!("<!-- alef:hash:{digest} -->\n\n# Doc\n\n```\nsample\n```\n"),
            ),
            (
                "stamp_after_fence_closes",
                format!("# Doc\n\n```\nsample\n```\n\n<!-- alef:hash:{digest} -->\nbody\n"),
            ),
            (
                "real_frontmatter_stamp",
                format!("---\ntitle: Doc\n---\n<!-- alef:hash:{digest} -->\nbody\n"),
            ),
            (
                "real_comment_continuation",
                format!("/*\n * alef:hash:{digest}\n */\nbody\n"),
            ),
        ];
        for (name, source) in &protect {
            assert!(
                is_hash_stamped_source(source),
                "{name}: a real stamp must stay protected: {source:?}"
            );
        }
    }

    /// Indented code blocks are a known gap, asserted so it stays deliberate.
    ///
    /// Suppressing a 4-space indent is the one rule in this area that would
    /// *widen* the skip instead of narrowing it, and indentation is structural —
    /// not a code-block marker — in the languages carrying 1236 of 1265 live
    /// stamps. Protecting the real indented stamp is worth more than catching the
    /// documented one, so this stays known-bad until the policy is ruled on.
    #[test]
    fn an_indented_code_block_is_a_known_gap_and_a_real_indented_stamp_stays_protected() {
        let digest = "a1b2c3d4".repeat(8);

        let documented = format!("# Doc\n\nGenerators write:\n\n    alef:hash:{digest}\n\nbody\n");
        assert!(
            is_hash_stamped_source(&documented),
            "known gap: an indented block is not yet recognized as a code context"
        );

        // The reason the gap is tolerable: the same rule that would close it also
        // strips protection from stamps that really are indented.
        let real = format!("<!--\n    alef:hash:{digest}\n-->\nbody\n");
        assert!(
            is_hash_stamped_source(&real),
            "an indented real stamp must stay protected"
        );
    }

    /// A stamp is a whole comment line. A token wrapped in markdown backticks is
    /// prose quoting a hash — the leading backtick is stripped as punctuation, so
    /// only the *trailing* character distinguishes the two.
    #[test]
    fn should_reject_a_digest_that_is_wrapped_rather_than_terminated() {
        let digest = "a".repeat(64);

        for wrapped in [
            format!("`alef:hash:{digest}`\nbody\n"),
            format!("(alef:hash:{digest})\nbody\n"),
            format!("\"alef:hash:{digest}\"\nbody\n"),
        ] {
            assert!(!is_hash_stamped_source(&wrapped), "wrapped token: {wrapped:?}");
        }

        // Bare, and every comment terminator a generator actually closes with.
        for stamped in [
            format!("// alef:hash:{digest}\nbody\n"),
            format!("<!-- alef:hash:{digest} -->\nbody\n"),
            format!(" * alef:hash:{digest} */\nbody\n"),
        ] {
            assert!(is_hash_stamped_source(&stamped), "real stamp: {stamped:?}");
        }
    }

    /// Token shape and header depth are independent axes. Tightening the shape
    /// must not narrow the window — the natural instinct when tightening a
    /// matcher is to tighten everything at once, and that would silently undo
    /// the generator-reach fix while every shape test still passed.
    #[test]
    fn tightening_the_digest_shape_must_not_move_the_depth_boundary() {
        let deepest = alef_stamped_source(9);
        assert!(is_hash_stamped_source(&deepest), "depth boundary narrowed");

        let beyond = alef_stamped_source(10);
        assert!(!is_hash_stamped_source(&beyond), "depth boundary widened");
    }

    /// The #10 fix must survive the wider window: the extra lines are exactly
    /// where ordinary `use` statements live.
    #[test]
    fn should_still_reject_ordinary_paths_inside_the_wider_window() {
        for ordinary in [
            format!("{}use a::hash::b;\n", "// filler\n".repeat(6)),
            format!("{}a:hash:b\n", "// filler\n".repeat(6)),
            format!(
                "{}// see example.com/alef/hash/deadbeef12345678\n",
                "// filler\n".repeat(6)
            ),
        ] {
            assert!(!is_generated_source(&ordinary), "source: {ordinary:?}");
            assert!(!is_hash_stamped_source(&ordinary), "source: {ordinary:?}");
        }
    }

    #[test]
    fn recognizes_generated_markers_after_yaml_frontmatter() {
        let source = "---\r\nname: api\r\ndescription: generated API docs\r\n---\r\n\r\n\
                      <!-- This file is auto-generated. DO NOT EDIT. -->\r\n\
                      <!-- alef:hash:a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef -->\r\n\
                      # Heading\r\n";

        assert!(
            is_generated_source(source),
            "generated banner below frontmatter was missed"
        );
        assert!(
            is_hash_stamped_source(source),
            "hash stamp below frontmatter was missed"
        );
    }

    #[test]
    fn unterminated_yaml_frontmatter_does_not_expand_marker_scan() {
        let source = "---\nname: api\n# alef:hash:a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef\n";
        assert!(!is_generated_source(source));
        assert!(!is_hash_stamped_source(source));
    }

    /// Both windows are measured from the end of the frontmatter block, not from
    /// byte 0 — see [`generated_header_region`]. These fixtures are the ones that
    /// tell the two models apart: the stamp sits at post-frontmatter line 5,
    /// which is raw line 8, so a refactor that dropped the frontmatter stripping
    /// and counted from byte 0 would report "outside the window" and fail here.
    ///
    /// Starlight/Astro reference pages are the live instance — frontmatter, a
    /// blank line, the banner, then the stamp — and a consumer has 21 of them.
    #[test]
    fn windows_are_measured_after_the_frontmatter_block() {
        let stamped = "---\nname: api\n---\n1\n2\n3\n4\n5\n# alef:hash:a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef\n";
        assert!(
            is_hash_stamped_source(stamped),
            "a stamp at post-frontmatter line 5 is inside the producer's reach and must be protected"
        );

        // The prose banners keep the narrow window, also measured post-frontmatter.
        let banner = "---\nname: api\n---\n1\n2\n3\n4\n5\n# DO NOT EDIT\n";
        assert!(
            !is_generated_source(banner),
            "a prose banner past the banner window must stay ordinary source"
        );
    }

    /// The wider window is still bounded. A stamp deeper than the producer's own
    /// reader accepts must not silently drop the file out of the format gate.
    #[test]
    fn structured_stamp_beyond_the_post_frontmatter_window_is_not_generated() {
        let mut source = String::from("---\nname: api\n---\n");
        for line in 1..=HASH_STAMP_HEADER_LINES {
            source.push_str(&format!("{line}\n"));
        }
        source.push_str("# alef:hash:a3f1c2d4e5b6a7980123456789abcdef0123456789abcdef0123456789abcdef\n");
        assert!(!is_generated_source(&source));
        assert!(!is_hash_stamped_source(&source));
    }
}
